// AUTO-GENERATED BY CLAUDE
using GamePlatform.Application.DTOs.Wallet;
using GamePlatform.Application.Interfaces;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Interfaces;

namespace GamePlatform.Application.UseCases.Wallet;

public partial class WalletService : IWalletService
{
    private readonly IWalletRepository _walletRepository;
    private readonly IDepositRequestRepository _depositRequestRepository;
    private readonly IWithdrawRequestRepository _withdrawRequestRepository;
    private readonly IUserBankCardRepository _bankCardRepository;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ITimeProvider _timeProvider;

    public WalletService(
        IWalletRepository walletRepository,
        IDepositRequestRepository depositRequestRepository,
        IWithdrawRequestRepository withdrawRequestRepository,
        IUserBankCardRepository bankCardRepository,
        IUnitOfWork unitOfWork,
        ITimeProvider timeProvider)
    {
        _walletRepository = walletRepository;
        _depositRequestRepository = depositRequestRepository;
        _withdrawRequestRepository = withdrawRequestRepository;
        _bankCardRepository = bankCardRepository;
        _unitOfWork = unitOfWork;
        _timeProvider = timeProvider;
    }

    #region 余额查询

    public async Task<WalletBalanceResponse> GetBalanceAsync(Guid userId)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId);
        if (wallet == null)
        {
            wallet = Domain.Entities.Wallet.Create(userId, _timeProvider.Now);
            await _walletRepository.AddAsync(wallet);
            await _unitOfWork.SaveChangesAsync();
        }

        return new WalletBalanceResponse
        {
            UserId = userId,
            Balance = wallet.Balance,
            FrozenBalance = wallet.FrozenBalance,
            AvailableBalance = wallet.AvailableBalance
        };
    }

    #endregion

    #region 管理员调整

    public async Task<AdminAdjustWalletResponse> AdminDepositAsync(AdminAdjustWalletRequest request)
    {
        if (request.Amount <= 0)
            throw new ArgumentException("充值金额必须大于0");

        var wallet = await GetOrCreateWalletAsync(request.UserId);
        var now = _timeProvider.Now;
        var expectedVersion = wallet.Version;

        var transaction = wallet.Credit(request.Amount, TransactionType.AdminDeposit, request.Reason, now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
            throw new InvalidOperationException("CAS更新失败 - 检测到并发修改");

        await _walletRepository.AddTransactionAsync(transaction);
        await _unitOfWork.SaveChangesAsync();

        return new AdminAdjustWalletResponse
        {
            TransactionId = transaction.Id,
            BalanceBefore = transaction.BalanceBefore,
            BalanceAfter = transaction.BalanceAfter
        };
    }

    public async Task<AdminAdjustWalletResponse> AdminWithdrawAsync(AdminAdjustWalletRequest request)
    {
        if (request.Amount <= 0)
            throw new ArgumentException("扣款金额必须大于0");

        var wallet = await GetOrCreateWalletAsync(request.UserId);
        var now = _timeProvider.Now;
        var expectedVersion = wallet.Version;

        var transaction = wallet.Debit(request.Amount, TransactionType.AdminWithdraw, request.Reason, now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
            throw new InvalidOperationException("CAS更新失败 - 检测到并发修改");

        await _walletRepository.AddTransactionAsync(transaction);
        await _unitOfWork.SaveChangesAsync();

        return new AdminAdjustWalletResponse
        {
            TransactionId = transaction.Id,
            BalanceBefore = transaction.BalanceBefore,
            BalanceAfter = transaction.BalanceAfter
        };
    }

    #endregion

    #region 对账

    public async Task<ReconciliationResult> ReconcileAsync(Guid userId)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId)
            ?? throw new InvalidOperationException("钱包不存在");

        var calculatedBalance = await _walletRepository.GetTransactionsSumAsync(wallet.Id);
        var isConsistent = wallet.Balance == calculatedBalance;

        return new ReconciliationResult
        {
            WalletId = wallet.Id,
            UserId = userId,
            RecordedBalance = wallet.Balance,
            CalculatedBalance = calculatedBalance,
            IsConsistent = isConsistent,
            Difference = isConsistent ? null : wallet.Balance - calculatedBalance
        };
    }

    #endregion

    #region 流水查询

    public async Task<PagedTransactionResponse> GetTransactionsAsync(Guid userId, int page, int pageSize)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId);
        if (wallet == null)
        {
            return new PagedTransactionResponse
            {
                Items = [],
                TotalCount = 0,
                Page = page,
                PageSize = pageSize,
                TotalPages = 0
            };
        }

        var transactions = await _walletRepository.GetTransactionsAsync(wallet.Id, page, pageSize);

        return new PagedTransactionResponse
        {
            Items = transactions.Select(t => new TransactionRecordResponse
            {
                Id = t.Id,
                Type = new TransactionTypeInfo { Code = (int)t.Type, Name = t.Type.ToString() },
                Amount = t.Amount,
                BalanceBefore = t.BalanceBefore,
                BalanceAfter = t.BalanceAfter,
                Description = t.Description,
                CreatedAt = t.CreatedAt,
                InternalOrderId = t.InternalOrderId
            }).ToList(),
            TotalCount = transactions.Count,
            Page = page,
            PageSize = pageSize,
            TotalPages = 1
        };
    }

    #endregion

    #region 充值申请

    public async Task<DepositRequestResponse> CreateDepositRequestAsync(Guid userId, DepositRequestRequest request)
    {
        if (request.Amount <= 0)
            throw new ArgumentException("充值金额必须大于0");

        var now = _timeProvider.Now;
        var internalOrderId = GenerateInternalOrderId("DP");

        var depositRequest = Domain.Entities.DepositRequest.Create(
            userId,
            internalOrderId,
            request.Amount,
            request.PaymentMethod,
            now);

        await _depositRequestRepository.AddAsync(depositRequest);
        await _unitOfWork.SaveChangesAsync();

        return new DepositRequestResponse
        {
            RequestId = depositRequest.Id,
            InternalOrderId = depositRequest.InternalOrderId,
            Amount = depositRequest.Amount,
            Status = depositRequest.Status.ToString(),
            CreatedAt = depositRequest.CreatedAt
        };
    }

    public async Task<DepositRequestResponse> ApproveDepositRequestAsync(Guid requestId, string adminUserId)
    {
        var depositRequest = await _depositRequestRepository.GetByIdAsync(requestId)
            ?? throw new InvalidOperationException("充值申请不存在");

        var wallet = await GetOrCreateWalletAsync(depositRequest.UserId);
        var now = _timeProvider.Now;
        var expectedVersion = wallet.Version;

        var transaction = wallet.Credit(depositRequest.Amount, TransactionType.Deposit, "充值到账", now);
        depositRequest.Confirm(depositRequest.InternalOrderId, now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
            throw new InvalidOperationException("CAS更新失败");

        await _walletRepository.AddTransactionAsync(transaction);
        await _unitOfWork.SaveChangesAsync();

        return new DepositRequestResponse
        {
            RequestId = depositRequest.Id,
            InternalOrderId = depositRequest.InternalOrderId,
            Amount = depositRequest.Amount,
            Status = depositRequest.Status.ToString(),
            CreatedAt = depositRequest.CreatedAt
        };
    }

    public async Task<DepositRequestResponse> RejectDepositRequestAsync(Guid requestId, string reason, string adminUserId)
    {
        var depositRequest = await _depositRequestRepository.GetByIdAsync(requestId)
            ?? throw new InvalidOperationException("充值申请不存在");

        var now = _timeProvider.Now;
        depositRequest.Fail(reason, now);

        await _unitOfWork.SaveChangesAsync();

        return new DepositRequestResponse
        {
            RequestId = depositRequest.Id,
            InternalOrderId = depositRequest.InternalOrderId,
            Amount = depositRequest.Amount,
            Status = depositRequest.Status.ToString(),
            CreatedAt = depositRequest.CreatedAt
        };
    }

    public async Task<PagedRequestRecordResponse> GetDepositRequestsAsync(string? status, int page, int pageSize)
    {
        DepositStatus? statusEnum = null;
        if (!string.IsNullOrEmpty(status) && Enum.TryParse<DepositStatus>(status, out var parsed))
        {
            statusEnum = parsed;
        }

        var requests = await _depositRequestRepository.GetByStatusAsync(statusEnum ?? DepositStatus.Pending, page, pageSize);

        return new PagedRequestRecordResponse
        {
            Items = requests.Select(r => new RequestRecordResponse
            {
                Id = r.Id,
                InternalOrderId = r.InternalOrderId,
                Amount = r.Amount,
                Status = r.Status.ToString(),
                ErrorMessage = r.ErrorMessage,
                CreatedAt = r.CreatedAt,
                UpdatedAt = r.UpdatedAt
            }).ToList(),
            TotalCount = requests.Count,
            Page = page,
            PageSize = pageSize,
            TotalPages = 1
        };
    }

    public async Task<PagedRequestRecordResponse> GetUserDepositRequestsAsync(Guid userId, int page, int pageSize)
    {
        var requests = await _depositRequestRepository.GetByUserIdAsync(userId, page, pageSize);

        return new PagedRequestRecordResponse
        {
            Items = requests.Select(r => new RequestRecordResponse
            {
                Id = r.Id,
                InternalOrderId = r.InternalOrderId,
                Amount = r.Amount,
                Status = r.Status.ToString(),
                ErrorMessage = r.ErrorMessage,
                CreatedAt = r.CreatedAt,
                UpdatedAt = r.UpdatedAt
            }).ToList(),
            TotalCount = requests.Count,
            Page = page,
            PageSize = pageSize,
            TotalPages = 1
        };
    }

    #endregion

    #region 提现申请

    public async Task<WithdrawRequestResponse> CreateWithdrawRequestAsync(Guid userId, WithdrawRequestRequest request)
    {
        if (request.Amount <= 0)
            throw new ArgumentException("提现金额必须大于0");

        var bankCard = await _bankCardRepository.GetByIdAsync(request.BankCardId)
            ?? throw new InvalidOperationException("银行卡不存在");

        if (bankCard.UserId != userId)
            throw new InvalidOperationException("银行卡不属于该用户");

        var wallet = await _walletRepository.GetByUserIdAsync(userId)
            ?? throw new InvalidOperationException("钱包不存在");

        if (wallet.AvailableBalance < request.Amount)
            throw new InsufficientBalanceException(wallet.AvailableBalance, request.Amount);

        var now = _timeProvider.Now;
        var internalOrderId = GenerateInternalOrderId("WD");

        // 冻结余额
        wallet.Freeze(request.Amount, now);
        var expectedVersion = wallet.Version - 1;

        var withdrawRequest = Domain.Entities.WithdrawRequest.Create(
            userId,
            internalOrderId,
            request.Amount,
            request.BankCardId,
            now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
            throw new InvalidOperationException("CAS更新失败");

        await _withdrawRequestRepository.AddAsync(withdrawRequest);
        await _unitOfWork.SaveChangesAsync();

        return new WithdrawRequestResponse
        {
            RequestId = withdrawRequest.Id,
            InternalOrderId = withdrawRequest.InternalOrderId,
            Amount = withdrawRequest.Amount,
            Status = withdrawRequest.Status.ToString(),
            CreatedAt = withdrawRequest.CreatedAt
        };
    }

    public async Task<WithdrawRequestResponse> ApproveWithdrawRequestAsync(Guid requestId, string adminUserId)
    {
        var withdrawRequest = await _withdrawRequestRepository.GetByIdAsync(requestId)
            ?? throw new InvalidOperationException("提现申请不存在");

        var wallet = await _walletRepository.GetByUserIdAsync(withdrawRequest.UserId)
            ?? throw new InvalidOperationException("钱包不存在");

        var now = _timeProvider.Now;
        var expectedVersion = wallet.Version;

        var transaction = wallet.ConfirmFrozenDebit(withdrawRequest.Amount, TransactionType.Withdrawal, "提现到账", now);
        withdrawRequest.Approve(now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
            throw new InvalidOperationException("CAS更新失败");

        await _walletRepository.AddTransactionAsync(transaction);
        await _unitOfWork.SaveChangesAsync();

        return new WithdrawRequestResponse
        {
            RequestId = withdrawRequest.Id,
            InternalOrderId = withdrawRequest.InternalOrderId,
            Amount = withdrawRequest.Amount,
            Status = withdrawRequest.Status.ToString(),
            CreatedAt = withdrawRequest.CreatedAt
        };
    }

    public async Task<WithdrawRequestResponse> RejectWithdrawRequestAsync(Guid requestId, string reason, string adminUserId)
    {
        var withdrawRequest = await _withdrawRequestRepository.GetByIdAsync(requestId)
            ?? throw new InvalidOperationException("提现申请不存在");

        var wallet = await _walletRepository.GetByUserIdAsync(withdrawRequest.UserId)
            ?? throw new InvalidOperationException("钱包不存在");

        var now = _timeProvider.Now;
        var expectedVersion = wallet.Version;

        // 解冻余额
        wallet.Unfreeze(withdrawRequest.Amount, now);
        withdrawRequest.Reject(reason, now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
            throw new InvalidOperationException("CAS更新失败");

        await _unitOfWork.SaveChangesAsync();

        return new WithdrawRequestResponse
        {
            RequestId = withdrawRequest.Id,
            InternalOrderId = withdrawRequest.InternalOrderId,
            Amount = withdrawRequest.Amount,
            Status = withdrawRequest.Status.ToString(),
            CreatedAt = withdrawRequest.CreatedAt
        };
    }

    public async Task<PagedRequestRecordResponse> GetWithdrawRequestsAsync(string? status, int page, int pageSize)
    {
        WithdrawStatus? statusEnum = null;
        if (!string.IsNullOrEmpty(status) && Enum.TryParse<WithdrawStatus>(status, out var parsed))
        {
            statusEnum = parsed;
        }

        var requests = await _withdrawRequestRepository.GetByStatusAsync(statusEnum ?? WithdrawStatus.Pending, page, pageSize);

        return new PagedRequestRecordResponse
        {
            Items = requests.Select(r => new RequestRecordResponse
            {
                Id = r.Id,
                InternalOrderId = r.InternalOrderId,
                Amount = r.Amount,
                Status = r.Status.ToString(),
                ErrorMessage = r.RejectionReason,
                CreatedAt = r.CreatedAt,
                UpdatedAt = r.UpdatedAt
            }).ToList(),
            TotalCount = requests.Count,
            Page = page,
            PageSize = pageSize,
            TotalPages = 1
        };
    }

    public async Task<PagedRequestRecordResponse> GetUserWithdrawRequestsAsync(Guid userId, int page, int pageSize)
    {
        var requests = await _withdrawRequestRepository.GetByUserIdAsync(userId, page, pageSize);

        return new PagedRequestRecordResponse
        {
            Items = requests.Select(r => new RequestRecordResponse
            {
                Id = r.Id,
                InternalOrderId = r.InternalOrderId,
                Amount = r.Amount,
                Status = r.Status.ToString(),
                ErrorMessage = r.RejectionReason,
                CreatedAt = r.CreatedAt,
                UpdatedAt = r.UpdatedAt
            }).ToList(),
            TotalCount = requests.Count,
            Page = page,
            PageSize = pageSize,
            TotalPages = 1
        };
    }

    #endregion

    #region Helper Methods

    private async Task<Domain.Entities.Wallet> GetOrCreateWalletAsync(Guid userId)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId);
        if (wallet == null)
        {
            wallet = Domain.Entities.Wallet.Create(userId, _timeProvider.Now);
            await _walletRepository.AddAsync(wallet);
            await _unitOfWork.SaveChangesAsync();
        }
        return wallet;
    }

    private static string GenerateInternalOrderId(string prefix)
    {
        return $"{prefix}{DateTime.Now:yyyyMMddHHmmssfff}{Guid.NewGuid().ToString("N")[..8].ToUpper()}";
    }

    #endregion
}
