// AUTO-GENERATED BY CLAUDE
using GamePlatform.Application.DTOs.Wallet;
using GamePlatform.Application.Interfaces;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Interfaces;

namespace GamePlatform.Application.UseCases.Wallet;

/// <summary>
/// 钱包服务实现
/// </summary>
public class WalletService : IWalletService
{
    private readonly IWalletRepository _walletRepository;
    private readonly IDepositRequestRepository _depositRequestRepository;
    private readonly IWithdrawRequestRepository _withdrawRequestRepository;
    private readonly IUserBankCardRepository _bankCardRepository;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ITimeProvider _timeProvider;

    public WalletService(
        IWalletRepository walletRepository,
        IDepositRequestRepository depositRequestRepository,
        IWithdrawRequestRepository withdrawRequestRepository,
        IUserBankCardRepository bankCardRepository,
        IUnitOfWork unitOfWork,
        ITimeProvider timeProvider)
    {
        _walletRepository = walletRepository;
        _depositRequestRepository = depositRequestRepository;
        _withdrawRequestRepository = withdrawRequestRepository;
        _bankCardRepository = bankCardRepository;
        _unitOfWork = unitOfWork;
        _timeProvider = timeProvider;
    }

    public async Task<WalletBalanceResponse> GetBalanceAsync(Guid userId)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId);
        if (wallet == null)
        {
            wallet = Domain.Entities.Wallet.Create(userId, _timeProvider.Now);
            await _walletRepository.AddAsync(wallet);
            await _unitOfWork.SaveChangesAsync();
        }

        return new WalletBalanceResponse
        {
            UserId = userId,
            Balance = wallet.Balance,
            FrozenBalance = wallet.FrozenBalance,
            AvailableBalance = wallet.AvailableBalance
        };
    }

    public async Task<AdminAdjustWalletResponse> AdminDepositAsync(AdminAdjustWalletRequest request)
    {
        if (request.Amount <= 0)
        {
            throw new ArgumentException("Amount must be positive");
        }

        var wallet = await GetOrCreateWalletAsync(request.UserId);
        var now = _timeProvider.Now;
        var expectedVersion = wallet.Version;

        var transaction = wallet.Credit(
            request.Amount,
            TransactionType.AdminDeposit,
            request.Reason,
            now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
        {
            throw new InvalidOperationException("CAS update failed - concurrent modification detected");
        }

        await _walletRepository.AddTransactionAsync(transaction);
        await _unitOfWork.SaveChangesAsync();

        return new AdminAdjustWalletResponse
        {
            TransactionId = transaction.Id,
            BalanceBefore = transaction.BalanceBefore,
            BalanceAfter = transaction.BalanceAfter
        };
    }

    public async Task<AdminAdjustWalletResponse> AdminWithdrawAsync(AdminAdjustWalletRequest request)
    {
        if (request.Amount <= 0)
        {
            throw new ArgumentException("Amount must be positive");
        }

        var wallet = await GetOrCreateWalletAsync(request.UserId);
        var now = _timeProvider.Now;
        var expectedVersion = wallet.Version;

        var transaction = wallet.Debit(
            request.Amount,
            TransactionType.AdminWithdraw,
            request.Reason,
            now);

        var success = await _walletRepository.UpdateWithCasAsync(wallet, expectedVersion);
        if (!success)
        {
            throw new InvalidOperationException("CAS update failed - concurrent modification detected");
        }

        await _walletRepository.AddTransactionAsync(transaction);
        await _unitOfWork.SaveChangesAsync();

        return new AdminAdjustWalletResponse
        {
            TransactionId = transaction.Id,
            BalanceBefore = transaction.BalanceBefore,
            BalanceAfter = transaction.BalanceAfter
        };
    }

    public async Task<ReconciliationResult> ReconcileAsync(Guid userId)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId);
        if (wallet == null)
        {
            throw new InvalidOperationException("Wallet not found");
        }

        var calculatedBalance = await _walletRepository.GetTransactionsSumAsync(wallet.Id);
        var isConsistent = wallet.Balance == calculatedBalance;

        return new ReconciliationResult
        {
            WalletId = wallet.Id,
            UserId = userId,
            RecordedBalance = wallet.Balance,
            CalculatedBalance = calculatedBalance,
            IsConsistent = isConsistent,
            Difference = isConsistent ? null : wallet.Balance - calculatedBalance
        };
    }

    public async Task<PagedTransactionResponse> GetTransactionsAsync(Guid userId, int page, int pageSize)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId);
        if (wallet == null)
        {
            return new PagedTransactionResponse
            {
                Items = [],
                TotalCount = 0,
                Page = page,
                PageSize = pageSize,
                TotalPages = 0
            };
        }

        var transactions = await _walletRepository.GetTransactionsAsync(wallet.Id, page, pageSize);
        
        // TODO: Get total count from repository

        return new PagedTransactionResponse
        {
            Items = transactions.Select(t => new TransactionRecordResponse
            {
                Id = t.Id,
                Type = new TransactionTypeInfo { Code = (int)t.Type, Name = t.Type.ToString() },
                Amount = t.Amount,
                BalanceBefore = t.BalanceBefore,
                BalanceAfter = t.BalanceAfter,
                Description = t.Description,
                CreatedAt = t.CreatedAt,
                InternalOrderId = t.InternalOrderId
            }).ToList(),
            TotalCount = transactions.Count,
            Page = page,
            PageSize = pageSize,
            TotalPages = 1
        };
    }

    #region 充值申请

    public async Task<DepositRequestResponse> CreateDepositRequestAsync(Guid userId, DepositRequestRequest request)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<DepositRequestResponse> ApproveDepositRequestAsync(Guid requestId, string adminUserId)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<DepositRequestResponse> RejectDepositRequestAsync(Guid requestId, string reason, string adminUserId)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<PagedRequestRecordResponse> GetDepositRequestsAsync(string? status, int page, int pageSize)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<PagedRequestRecordResponse> GetUserDepositRequestsAsync(Guid userId, int page, int pageSize)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    #endregion

    #region 提现申请

    public async Task<WithdrawRequestResponse> CreateWithdrawRequestAsync(Guid userId, WithdrawRequestRequest request)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<WithdrawRequestResponse> ApproveWithdrawRequestAsync(Guid requestId, string adminUserId)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<WithdrawRequestResponse> RejectWithdrawRequestAsync(Guid requestId, string reason, string adminUserId)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<PagedRequestRecordResponse> GetWithdrawRequestsAsync(string? status, int page, int pageSize)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    public async Task<PagedRequestRecordResponse> GetUserWithdrawRequestsAsync(Guid userId, int page, int pageSize)
    {
        // TODO: Implement
        throw new NotImplementedException();
    }

    #endregion

    private async Task<Domain.Entities.Wallet> GetOrCreateWalletAsync(Guid userId)
    {
        var wallet = await _walletRepository.GetByUserIdAsync(userId);
        if (wallet == null)
        {
            wallet = Domain.Entities.Wallet.Create(userId, _timeProvider.Now);
            await _walletRepository.AddAsync(wallet);
            await _unitOfWork.SaveChangesAsync();
        }
        return wallet;
    }
}
