// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Application.Interfaces;

/// <summary>
/// 管理员操作日志仓储接口
/// </summary>
/// <remarks>
/// 注: AdminActionLog 实体将在后续阶段实现
/// </remarks>
public interface IAdminActionLogRepository
{
    // TODO: 待 AdminActionLog 实体实现后取消注释
    // Task AddAsync(AdminActionLog log);
    // Task<AdminActionLog?> GetByIdempotencyKeyAsync(string idempotencyKey);
    // Task<IReadOnlyList<AdminActionLog>> GetPagedAsync(int page, int pageSize, int? level = null);
    // Task<IReadOnlyList<AdminActionLog>> GetByTargetAsync(string targetType, Guid targetId);
}
