// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Application.Interfaces;

/// <summary>
/// 时间提供者接口
/// </summary>
/// <remarks>
/// Application 层获取当前本地时间，Domain 层通过参数注入。
/// 所有时间必须使用本地时间，禁止使用 UTC。
/// </remarks>
public interface ITimeProvider
{
    /// <summary>
    /// 获取当前本地时间（禁止 UTC）
    /// </summary>
    DateTime Now { get; }
}

/// <summary>
/// 系统时间提供者（默认实现）
/// </summary>
public class SystemTimeProvider : ITimeProvider
{
    public DateTime Now => DateTime.Now;
}
