// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Application.Interfaces;

/// <summary>
/// 厂商回调日志仓储接口
/// </summary>
/// <remarks>
/// 注: VendorCallbackLog 实体将在后续阶段实现
/// </remarks>
public interface IVendorCallbackLogRepository
{
    // TODO: 待 VendorCallbackLog 实体实现后取消注释
    // Task AddAsync(VendorCallbackLog log);
    // Task<IReadOnlyList<VendorCallbackLog>> GetByOrderIdAsync(Guid orderId);
    // Task<IReadOnlyList<VendorCallbackLog>> GetPagedAsync(int page, int pageSize, string? vendorCode = null);
}
