// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Application.Interfaces;

/// <summary>
/// 厂商查询日志仓储接口
/// </summary>
/// <remarks>
/// 注: VendorQueryLog 实体将在后续阶段实现
/// </remarks>
public interface IVendorQueryLogRepository
{
    // TODO: 待 VendorQueryLog 实体实现后取消注释
    // Task AddAsync(VendorQueryLog log);
    // Task<int> GetAttemptCountAsync(Guid orderId);
    // Task<IReadOnlyList<VendorQueryLog>> GetByOrderIdAsync(Guid orderId);
    // Task<IReadOnlyList<VendorQueryLog>> GetPagedAsync(int page, int pageSize);
}
