// AUTO-GENERATED BY CLAUDE
using GamePlatform.Application.DTOs.Wallet;

namespace GamePlatform.Application.Interfaces;

/// <summary>
/// 钱包服务接口
/// </summary>
public interface IWalletService
{
    /// <summary>
    /// 获取用户钱包余额
    /// </summary>
    Task<WalletBalanceResponse> GetBalanceAsync(Guid userId);

    /// <summary>
    /// 管理员充值（正数调整）
    /// </summary>
    Task<AdminAdjustWalletResponse> AdminDepositAsync(AdminAdjustWalletRequest request);

    /// <summary>
    /// 管理员扣款（负数调整）
    /// </summary>
    Task<AdminAdjustWalletResponse> AdminWithdrawAsync(AdminAdjustWalletRequest request);

    /// <summary>
    /// 钱包对账（检查余额与流水一致性）
    /// </summary>
    Task<ReconciliationResult> ReconcileAsync(Guid userId);

    /// <summary>
    /// 获取钱包流水记录
    /// </summary>
    Task<PagedTransactionResponse> GetTransactionsAsync(Guid userId, int page, int pageSize);

    #region 充值申请

    /// <summary>
    /// 创建充值申请
    /// </summary>
    Task<DepositRequestResponse> CreateDepositRequestAsync(Guid userId, DepositRequestRequest request);

    /// <summary>
    /// 审批充值申请（管理员）
    /// </summary>
    Task<DepositRequestResponse> ApproveDepositRequestAsync(Guid requestId, string adminUserId);

    /// <summary>
    /// 拒绝充值申请（管理员）
    /// </summary>
    Task<DepositRequestResponse> RejectDepositRequestAsync(Guid requestId, string reason, string adminUserId);

    /// <summary>
    /// 获取充值申请列表（管理员）
    /// </summary>
    Task<PagedRequestRecordResponse> GetDepositRequestsAsync(string? status, int page, int pageSize);

    /// <summary>
    /// 获取用户的充值申请列表
    /// </summary>
    Task<PagedRequestRecordResponse> GetUserDepositRequestsAsync(Guid userId, int page, int pageSize);

    #endregion

    #region 提现申请

    /// <summary>
    /// 创建提现申请（含冻结余额）
    /// </summary>
    Task<WithdrawRequestResponse> CreateWithdrawRequestAsync(Guid userId, WithdrawRequestRequest request);

    /// <summary>
    /// 审批提现申请（确认扣款）
    /// </summary>
    Task<WithdrawRequestResponse> ApproveWithdrawRequestAsync(Guid requestId, string adminUserId);

    /// <summary>
    /// 拒绝提现申请（解冻余额）
    /// </summary>
    Task<WithdrawRequestResponse> RejectWithdrawRequestAsync(Guid requestId, string reason, string adminUserId);

    /// <summary>
    /// 获取提现申请列表（管理员）
    /// </summary>
    Task<PagedRequestRecordResponse> GetWithdrawRequestsAsync(string? status, int page, int pageSize);

    /// <summary>
    /// 获取用户的提现申请列表
    /// </summary>
    Task<PagedRequestRecordResponse> GetUserWithdrawRequestsAsync(Guid userId, int page, int pageSize);

    #endregion
}
