// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Application.DTOs.Wallet;
using GamePlatform.Application.Interfaces;
using GamePlatform.Application.UseCases.Wallet;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Interfaces;
using Moq;
using Xunit;

namespace GamePlatform.Application.Tests.Services;

public class WalletServiceTests
{
    private readonly Mock<IWalletRepository> _walletRepoMock;
    private readonly Mock<IDepositRequestRepository> _depositRepoMock;
    private readonly Mock<IWithdrawRequestRepository> _withdrawRepoMock;
    private readonly Mock<IUserBankCardRepository> _bankCardRepoMock;
    private readonly Mock<IUnitOfWork> _unitOfWorkMock;
    private readonly Mock<ITimeProvider> _timeProviderMock;
    private readonly IWalletService _sut;

    public WalletServiceTests()
    {
        _walletRepoMock = new Mock<IWalletRepository>();
        _depositRepoMock = new Mock<IDepositRequestRepository>();
        _withdrawRepoMock = new Mock<IWithdrawRequestRepository>();
        _bankCardRepoMock = new Mock<IUserBankCardRepository>();
        _unitOfWorkMock = new Mock<IUnitOfWork>();
        _timeProviderMock = new Mock<ITimeProvider>();
        
        _sut = new WalletService(
            _walletRepoMock.Object,
            _depositRepoMock.Object,
            _withdrawRepoMock.Object,
            _bankCardRepoMock.Object,
            _unitOfWorkMock.Object,
            _timeProviderMock.Object);
    }

    #region GetBalance Tests

    [Fact]
    public async Task GetBalanceAsync_WhenWalletExists_ReturnsBalance()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        wallet.Credit(100m, TransactionType.Deposit, "Initial", DateTime.Now);
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);

        // Act
        var result = await _sut.GetBalanceAsync(userId);

        // Assert
        result.Should().NotBeNull();
        result.UserId.Should().Be(userId);
        result.Balance.Should().Be(100m);
    }

    [Fact]
    public async Task GetBalanceAsync_WhenWalletNotExists_CreatesNewWallet()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var now = DateTime.Now;
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync((Domain.Entities.Wallet?)null);
        _timeProviderMock.Setup(x => x.Now).Returns(now);
        _unitOfWorkMock.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        // Act
        var result = await _sut.GetBalanceAsync(userId);

        // Assert
        result.Should().NotBeNull();
        result.Balance.Should().Be(0m);
        _walletRepoMock.Verify(x => x.AddAsync(It.IsAny<Domain.Entities.Wallet>()), Times.Once);
    }

    #endregion

    #region AdminDeposit Tests

    [Fact]
    public async Task AdminDepositAsync_WhenValidRequest_ReturnsTransaction()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        var now = DateTime.Now;
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);
        _timeProviderMock.Setup(x => x.Now).Returns(now);
        _walletRepoMock.Setup(x => x.UpdateWithCasAsync(wallet, 0))
            .ReturnsAsync(true);
        _unitOfWorkMock.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var request = new AdminAdjustWalletRequest
        {
            UserId = userId,
            Amount = 100m,
            Reason = "管理员充值",
            IsDebit = false
        };

        // Act
        var result = await _sut.AdminDepositAsync(request);

        // Assert
        result.Should().NotBeNull();
        result.BalanceBefore.Should().Be(0m);
        result.BalanceAfter.Should().Be(100m);
    }

    [Fact]
    public async Task AdminDepositAsync_WithNegativeAmount_ThrowsException()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);

        var request = new AdminAdjustWalletRequest
        {
            UserId = userId,
            Amount = -50m,
            Reason = "Invalid",
            IsDebit = false
        };

        // Act & Assert
        await Assert.ThrowsAsync<ArgumentException>(
            () => _sut.AdminDepositAsync(request));
    }

    #endregion

    #region AdminWithdraw Tests

    [Fact]
    public async Task AdminWithdrawAsync_WhenSufficientBalance_ReturnsTransaction()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        wallet.Credit(200m, TransactionType.Deposit, "Initial", DateTime.Now);
        var now = DateTime.Now;
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);
        _timeProviderMock.Setup(x => x.Now).Returns(now);
        _walletRepoMock.Setup(x => x.UpdateWithCasAsync(wallet, 1))
            .ReturnsAsync(true);
        _unitOfWorkMock.Setup(x => x.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var request = new AdminAdjustWalletRequest
        {
            UserId = userId,
            Amount = 50m,
            Reason = "管理员扣款",
            IsDebit = true
        };

        // Act
        var result = await _sut.AdminWithdrawAsync(request);

        // Assert
        result.Should().NotBeNull();
        result.BalanceBefore.Should().Be(200m);
        result.BalanceAfter.Should().Be(150m);
    }

    [Fact]
    public async Task AdminWithdrawAsync_WhenInsufficientBalance_ThrowsException()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        wallet.Credit(50m, TransactionType.Deposit, "Initial", DateTime.Now);
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);

        var request = new AdminAdjustWalletRequest
        {
            UserId = userId,
            Amount = 100m,
            Reason = "Too much",
            IsDebit = true
        };

        // Act & Assert
        await Assert.ThrowsAsync<InsufficientBalanceException>(
            () => _sut.AdminWithdrawAsync(request));
    }

    #endregion

    #region CAS Conflict Tests

    [Fact]
    public async Task AdminDepositAsync_WhenCasConflict_ThrowsException()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        var now = DateTime.Now;
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);
        _timeProviderMock.Setup(x => x.Now).Returns(now);
        _walletRepoMock.Setup(x => x.UpdateWithCasAsync(wallet, 0))
            .ReturnsAsync(false); // CAS conflict

        var request = new AdminAdjustWalletRequest
        {
            UserId = userId,
            Amount = 100m,
            Reason = "管理员充值",
            IsDebit = false
        };

        // Act & Assert
        await Assert.ThrowsAsync<InvalidOperationException>(
            () => _sut.AdminDepositAsync(request));
    }

    #endregion

    #region Reconciliation Tests

    [Fact]
    public async Task ReconcileAsync_WhenBalancesMatch_ReturnsConsistent()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        wallet.Credit(100m, TransactionType.Deposit, "Initial", DateTime.Now);
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);
        _walletRepoMock.Setup(x => x.GetTransactionsSumAsync(wallet.Id))
            .ReturnsAsync(100m);

        // Act
        var result = await _sut.ReconcileAsync(userId);

        // Assert
        result.IsConsistent.Should().BeTrue();
        result.Difference.Should().BeNull();
    }

    [Fact]
    public async Task ReconcileAsync_WhenBalancesDoNotMatch_ReturnsInconsistent()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var wallet = Domain.Entities.Wallet.Create(userId, DateTime.Now);
        wallet.Credit(100m, TransactionType.Deposit, "Initial", DateTime.Now);
        
        _walletRepoMock.Setup(x => x.GetByUserIdAsync(userId))
            .ReturnsAsync(wallet);
        _walletRepoMock.Setup(x => x.GetTransactionsSumAsync(wallet.Id))
            .ReturnsAsync(90m); // Discrepancy

        // Act
        var result = await _sut.ReconcileAsync(userId);

        // Assert
        result.IsConsistent.Should().BeFalse();
        result.Difference.Should().Be(10m);
    }

    #endregion
}
