// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Infrastructure.Persistence.Configurations;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence;

/// <summary>
/// 应用程序数据库上下文
/// </summary>
public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    // Domain Entities
    public DbSet<UserProfile> UserProfiles => Set<UserProfile>();
    public DbSet<Wallet> Wallets => Set<Wallet>();
    public DbSet<WalletTransaction> WalletTransactions => Set<WalletTransaction>();
    public DbSet<GameOrder> GameOrders => Set<GameOrder>();
    public DbSet<VendorPlayerMapping> VendorPlayerMappings => Set<VendorPlayerMapping>();
    public DbSet<DepositRequest> DepositRequests => Set<DepositRequest>();
    public DbSet<WithdrawRequest> WithdrawRequests => Set<WithdrawRequest>();
    public DbSet<UserBankCard> UserBankCards => Set<UserBankCard>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Apply all entity configurations
        modelBuilder.ApplyConfiguration(new UserProfileConfiguration());
        modelBuilder.ApplyConfiguration(new WalletConfiguration());
        modelBuilder.ApplyConfiguration(new WalletTransactionConfiguration());
        modelBuilder.ApplyConfiguration(new GameOrderConfiguration());
        modelBuilder.ApplyConfiguration(new VendorPlayerMappingConfiguration());
        modelBuilder.ApplyConfiguration(new DepositRequestConfiguration());
        modelBuilder.ApplyConfiguration(new WithdrawRequestConfiguration());
        modelBuilder.ApplyConfiguration(new UserBankCardConfiguration());
    }
}
