// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Domain.Enums;

/// <summary>
/// 充值状态
/// </summary>
public enum DepositStatus
{
    /// <summary>
    /// 待处理
    /// </summary>
    Pending = 0,

    /// <summary>
    /// 已确认（三方已确认收到支付）
    /// </summary>
    Confirmed = 1,

    /// <summary>
    /// 已结算（余额已入账）
    /// </summary>
    Settled = 2,

    /// <summary>
    /// 已取消
    /// </summary>
    Cancelled = 3,

    /// <summary>
    /// 失败
    /// </summary>
    Failed = 4
}
