// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Domain.Enums;

/// <summary>
/// 游戏订单状态
/// </summary>
public enum OrderStatus
{
    Pending = 0,
    Confirmed = 2,
    Settled = 3,
    Cancelled = 4,
    Failed = 5
}
