// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Domain.Enums;

/// <summary>
/// 钱包交易类型
/// </summary>
public enum TransactionType
{
    /// <summary>
    /// 充值
    /// </summary>
    Deposit = 0,

    /// <summary>
    /// 提现
    /// </summary>
    Withdrawal = 1,

    /// <summary>
    /// 游戏转入（从平台扣款到厂商）
    /// </summary>
    GameTransferIn = 2,

    /// <summary>
    /// 游戏转出（从厂商回到平台）
    /// </summary>
    GameTransferOut = 3,

    /// <summary>
    /// 管理员调整
    /// </summary>
    AdminAdjust = 4,

    /// <summary>
    /// 退款
    /// </summary>
    Refund = 5
}
