// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Domain.Enums;

/// <summary>
/// 提现状态
/// </summary>
public enum WithdrawStatus
{
    /// <summary>
    /// 待审核
    /// </summary>
    Pending = 0,

    /// <summary>
    /// 已批准
    /// </summary>
    Approved = 1,

    /// <summary>
    /// 处理中（已提交到三方）
    /// </summary>
    Processing = 2,

    /// <summary>
    /// 已完成
    /// </summary>
    Completed = 3,

    /// <summary>
    /// 已拒绝
    /// </summary>
    Rejected = 4
}
