// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Rules;

/// <summary>
/// 充值状态机验证
/// </summary>
public static class DepositStateMachine
{
    private static readonly Dictionary<DepositStatus, HashSet<DepositStatus>> ValidTransitions;

    static DepositStateMachine()
    {
        ValidTransitions = new Dictionary<DepositStatus, HashSet<DepositStatus>>
        {
            [DepositStatus.Pending] = new HashSet<DepositStatus>
            {
                DepositStatus.Confirmed,
                DepositStatus.Failed,
                DepositStatus.Cancelled
            },
            [DepositStatus.Confirmed] = new HashSet<DepositStatus>
            {
                DepositStatus.Settled
            }
        };
    }

    /// <summary>
    /// 验证状态流转合法性
    /// </summary>
    public static void ValidateTransition(DepositStatus from, DepositStatus to)
    {
        if (!ValidTransitions.TryGetValue(from, out var validTargets))
        {
            throw new StateMachineException(from.ToString(), to.ToString());
        }

        if (!validTargets.Contains(to))
        {
            throw new StateMachineException(from.ToString(), to.ToString());
        }
    }
}
