// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Rules;

/// <summary>
/// 订单状态机验证
/// </summary>
public static class OrderStateMachine
{
    private static readonly Dictionary<OrderStatus, HashSet<OrderStatus>> ValidTransitions;

    static OrderStateMachine()
    {
        ValidTransitions = new Dictionary<OrderStatus, HashSet<OrderStatus>>
        {
            [OrderStatus.Pending] = new HashSet<OrderStatus>
            {
                OrderStatus.Confirmed,
                OrderStatus.Failed
            },
            [OrderStatus.Confirmed] = new HashSet<OrderStatus>
            {
                OrderStatus.Settled,
                OrderStatus.Cancelled
            }
        };
    }

    /// <summary>
    /// 验证状态流转合法性
    /// </summary>
    public static void ValidateTransition(OrderStatus from, OrderStatus to)
    {
        if (!ValidTransitions.TryGetValue(from, out var validTargets))
        {
            throw new InvalidStateTransitionException(from, to);
        }

        if (!validTargets.Contains(to))
        {
            throw new InvalidStateTransitionException(from, to);
        }
    }
}
