// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Rules;

/// <summary>
/// 钱包业务规则验证
/// </summary>
public static class WalletRules
{
    /// <summary>
    /// 验证金额必须大于零
    /// </summary>
    public static void ValidateAmount(decimal amount)
    {
        if (amount <= 0)
            throw new DomainException("Amount must be greater than zero.");
    }

    /// <summary>
    /// 验证余额充足（传入 AvailableBalance 而非 Balance）
    /// </summary>
    public static void ValidateSufficientBalance(decimal availableBalance, decimal amount)
    {
        if (availableBalance < amount)
            throw new InsufficientBalanceException(availableBalance, amount);
    }

    /// <summary>
    /// 验证冻结余额充足
    /// </summary>
    public static void ValidateSufficientFrozenBalance(decimal frozenBalance, decimal amount)
    {
        if (frozenBalance < amount)
            throw new DomainException($"Frozen balance {frozenBalance} is less than requested amount {amount}.");
    }
}

/// <summary>
/// 金额限额配置（Application 层使用，可通过 appsettings 配置）
/// </summary>
public class AmountLimitOptions
{
    /// <summary>
    /// 最小单笔充值
    /// </summary>
    public decimal MinDepositAmount { get; set; } = 10m;

    /// <summary>
    /// 最大单笔充值
    /// </summary>
    public decimal MaxDepositAmount { get; set; } = 50_000m;

    /// <summary>
    /// 最小单笔提现
    /// </summary>
    public decimal MinWithdrawAmount { get; set; } = 10m;

    /// <summary>
    /// 最大单笔提现
    /// </summary>
    public decimal MaxWithdrawAmount { get; set; } = 50_000m;

    /// <summary>
    /// 每日累计提现上限
    /// </summary>
    public decimal DailyWithdrawLimit { get; set; } = 100_000m;

    /// <summary>
    /// 最小游戏转入金额
    /// </summary>
    public decimal MinGameTransferAmount { get; set; } = 1m;
}
