// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Rules;

/// <summary>
/// 提现状态机验证
/// </summary>
public static class WithdrawStateMachine
{
    private static readonly Dictionary<WithdrawStatus, HashSet<WithdrawStatus>> ValidTransitions;

    static WithdrawStateMachine()
    {
        ValidTransitions = new Dictionary<WithdrawStatus, HashSet<WithdrawStatus>>
        {
            [WithdrawStatus.Pending] = new HashSet<WithdrawStatus>
            {
                WithdrawStatus.Approved,
                WithdrawStatus.Rejected
            },
            [WithdrawStatus.Approved] = new HashSet<WithdrawStatus>
            {
                WithdrawStatus.Processing
            },
            [WithdrawStatus.Processing] = new HashSet<WithdrawStatus>
            {
                WithdrawStatus.Completed
            }
        };
    }

    /// <summary>
    /// 验证状态流转合法性
    /// </summary>
    public static void ValidateTransition(WithdrawStatus from, WithdrawStatus to)
    {
        if (!ValidTransitions.TryGetValue(from, out var validTargets))
        {
            throw new StateMachineException(from.ToString(), to.ToString());
        }

        if (!validTargets.Contains(to))
        {
            throw new StateMachineException(from.ToString(), to.ToString());
        }
    }
}
