// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Rules;
using Xunit;

namespace GamePlatform.Domain.Tests.Rules;

public class OrderStateMachineTests
{
    #region Valid Transitions

    [Fact]
    public void ValidateTransition_PendingToConfirmed_ShouldNotThrow()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Pending, OrderStatus.Confirmed);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ValidateTransition_PendingToFailed_ShouldNotThrow()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Pending, OrderStatus.Failed);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ValidateTransition_ConfirmedToSettled_ShouldNotThrow()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Confirmed, OrderStatus.Settled);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ValidateTransition_ConfirmedToCancelled_ShouldNotThrow()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Confirmed, OrderStatus.Cancelled);

        // Assert
        act.Should().NotThrow();
    }

    #endregion

    #region Invalid Transitions - Pending

    [Fact]
    public void ValidateTransition_PendingToSettled_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Pending, OrderStatus.Settled);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>()
            .Where(e => e.FromStatus == OrderStatus.Pending && e.ToStatus == OrderStatus.Settled);
    }

    [Fact]
    public void ValidateTransition_PendingToCancelled_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Pending, OrderStatus.Cancelled);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>()
            .Where(e => e.FromStatus == OrderStatus.Pending && e.ToStatus == OrderStatus.Cancelled);
    }

    #endregion

    #region Invalid Transitions - Confirmed

    [Fact]
    public void ValidateTransition_ConfirmedToPending_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Confirmed, OrderStatus.Pending);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>()
            .Where(e => e.FromStatus == OrderStatus.Confirmed && e.ToStatus == OrderStatus.Pending);
    }

    [Fact]
    public void ValidateTransition_ConfirmedToFailed_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Confirmed, OrderStatus.Failed);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>()
            .Where(e => e.FromStatus == OrderStatus.Confirmed && e.ToStatus == OrderStatus.Failed);
    }

    #endregion

    #region Invalid Transitions - Settled (Terminal)

    [Fact]
    public void ValidateTransition_SettledToPending_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Settled, OrderStatus.Pending);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_SettledToConfirmed_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Settled, OrderStatus.Confirmed);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_SettledToCancelled_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Settled, OrderStatus.Cancelled);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_SettledToFailed_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Settled, OrderStatus.Failed);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    #endregion

    #region Invalid Transitions - Cancelled (Terminal)

    [Fact]
    public void ValidateTransition_CancelledToPending_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Cancelled, OrderStatus.Pending);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_CancelledToConfirmed_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Cancelled, OrderStatus.Confirmed);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_CancelledToSettled_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Cancelled, OrderStatus.Settled);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_CancelledToFailed_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Cancelled, OrderStatus.Failed);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    #endregion

    #region Invalid Transitions - Failed (Terminal)

    [Fact]
    public void ValidateTransition_FailedToPending_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Failed, OrderStatus.Pending);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_FailedToConfirmed_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Failed, OrderStatus.Confirmed);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_FailedToSettled_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Failed, OrderStatus.Settled);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    [Fact]
    public void ValidateTransition_FailedToCancelled_ShouldThrowInvalidStateTransitionException()
    {
        // Act
        var act = () => OrderStateMachine.ValidateTransition(OrderStatus.Failed, OrderStatus.Cancelled);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    #endregion
}
