// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Rules;
using Xunit;

namespace GamePlatform.Domain.Tests.Rules;

public class WalletRulesTests
{
    #region ValidateAmount Tests

    [Fact]
    public void ValidateAmount_PositiveAmount_ShouldPass()
    {
        // Arrange
        var amount = 100m;

        // Act
        var act = () => WalletRules.ValidateAmount(amount);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ValidateAmount_ZeroAmount_ShouldThrowDomainException()
    {
        // Arrange
        var amount = 0m;

        // Act
        var act = () => WalletRules.ValidateAmount(amount);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*greater than zero*");
    }

    [Fact]
    public void ValidateAmount_NegativeAmount_ShouldThrowDomainException()
    {
        // Arrange
        var amount = -1m;

        // Act
        var act = () => WalletRules.ValidateAmount(amount);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*greater than zero*");
    }

    #endregion

    #region ValidateSufficientBalance Tests

    [Fact]
    public void ValidateSufficientBalance_SufficientBalance_ShouldPass()
    {
        // Arrange
        var availableBalance = 500m;
        var amount = 400m;

        // Act
        var act = () => WalletRules.ValidateSufficientBalance(availableBalance, amount);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ValidateSufficientBalance_ExactBalance_ShouldPass()
    {
        // Arrange
        var availableBalance = 500m;
        var amount = 500m;

        // Act
        var act = () => WalletRules.ValidateSufficientBalance(availableBalance, amount);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ValidateSufficientBalance_InsufficientBalance_ShouldThrowInsufficientBalanceException()
    {
        // Arrange
        var availableBalance = 500m;
        var amount = 501m;

        // Act
        var act = () => WalletRules.ValidateSufficientBalance(availableBalance, amount);

        // Assert
        act.Should().Throw<InsufficientBalanceException>()
            .Where(e => e.AvailableBalance == availableBalance && e.RequestedAmount == amount);
    }

    #endregion

    #region ValidateSufficientFrozenBalance Tests

    [Fact]
    public void ValidateSufficientFrozenBalance_SufficientFrozenBalance_ShouldPass()
    {
        // Arrange
        var frozenBalance = 200m;
        var amount = 200m;

        // Act
        var act = () => WalletRules.ValidateSufficientFrozenBalance(frozenBalance, amount);

        // Assert
        act.Should().NotThrow();
    }

    [Fact]
    public void ValidateSufficientFrozenBalance_InsufficientFrozenBalance_ShouldThrowDomainException()
    {
        // Arrange
        var frozenBalance = 100m;
        var amount = 200m;

        // Act
        var act = () => WalletRules.ValidateSufficientFrozenBalance(frozenBalance, amount);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*Frozen balance*");
    }

    #endregion
}
