// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Application.DTOs.Wallet;

/// <summary>
/// 钱包余额响应
/// </summary>
public record WalletBalanceResponse
{
    public Guid UserId { get; init; }
    public decimal Balance { get; init; }
    public decimal FrozenBalance { get; init; }
    public decimal AvailableBalance { get; init; }
}

/// <summary>
/// 管理员调整钱包请求
/// </summary>
public record AdminAdjustWalletRequest
{
    public Guid UserId { get; init; }
    public decimal Amount { get; init; }
    public string Reason { get; init; } = string.Empty;
    public bool IsDebit { get; init; }  // true=扣款, false=充值
}

/// <summary>
/// 管理员调整钱包响应
/// </summary>
public record AdminAdjustWalletResponse
{
    public Guid TransactionId { get; init; }
    public decimal BalanceBefore { get; init; }
    public decimal BalanceAfter { get; init; }
}

/// <summary>
/// 对账结果
/// </summary>
public record ReconciliationResult
{
    public Guid WalletId { get; init; }
    public Guid UserId { get; init; }
    public decimal RecordedBalance { get; init; }
    public decimal CalculatedBalance { get; init; }
    public bool IsConsistent { get; init; }
    public decimal? Difference { get; init; }
}

/// <summary>
/// 流水记录响应
/// </summary>
public record TransactionRecordResponse
{
    public Guid Id { get; init; }
    public TransactionTypeInfo Type { get; init; }
    public decimal Amount { get; init; }
    public decimal BalanceBefore { get; init; }
    public decimal BalanceAfter { get; init; }
    public string Description { get; init; } = string.Empty;
    public DateTime CreatedAt { get; init; }
    public string? InternalOrderId { get; init; }
}

/// <summary>
/// 交易类型信息
/// </summary>
public record TransactionTypeInfo
{
    public int Code { get; init; }
    public string Name { get; init; } = string.Empty;
}

/// <summary>
/// 分页钱包流水响应
/// </summary>
public record PagedTransactionResponse
{
    public IReadOnlyList<TransactionRecordResponse> Items { get; init; } = [];
    public int TotalCount { get; init; }
    public int Page { get; init; }
    public int PageSize { get; init; }
    public int TotalPages { get; init; }
}

/// <summary>
/// 充值申请请求
/// </summary>
public record DepositRequestRequest
{
    public decimal Amount { get; init; }
    public string PaymentMethod { get; init; } = string.Empty;
}

/// <summary>
/// 充值申请响应
/// </summary>
public record DepositRequestResponse
{
    public Guid RequestId { get; init; }
    public string InternalOrderId { get; init; } = string.Empty;
    public decimal Amount { get; init; }
    public string Status { get; init; } = string.Empty;
    public DateTime CreatedAt { get; init; }
}

/// <summary>
/// 提现申请请求
/// </summary>
public record WithdrawRequestRequest
{
    public decimal Amount { get; init; }
    public Guid BankCardId { get; init; }
}

/// <summary>
/// 提现申请响应
/// </summary>
public record WithdrawRequestResponse
{
    public Guid RequestId { get; init; }
    public string InternalOrderId { get; init; } = string.Empty;
    public decimal Amount { get; init; }
    public string Status { get; init; } = string.Empty;
    public DateTime CreatedAt { get; init; }
}

/// <summary>
/// 审批请求
/// </summary>
public record ApprovalRequest
{
    public Guid RequestId { get; init; }
    public string? RejectionReason { get; init; }
}

/// <summary>
/// 申请记录响应
/// </summary>
public record RequestRecordResponse
{
    public Guid Id { get; init; }
    public string InternalOrderId { get; init; } = string.Empty;
    public decimal Amount { get; init; }
    public string Status { get; init; } = string.Empty;
    public string? ErrorMessage { get; init; }
    public string? RejectionReason { get; init; }
    public DateTime CreatedAt { get; init; }
    public DateTime UpdatedAt { get; init; }
}

/// <summary>
/// 分页申请记录响应
/// </summary>
public record PagedRequestRecordResponse
{
    public IReadOnlyList<RequestRecordResponse> Items { get; init; } = [];
    public int TotalCount { get; init; }
    public int Page { get; init; }
    public int PageSize { get; init; }
    public int TotalPages { get; init; }
}
