// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence.Repositories;

/// <summary>
/// 充值申请仓储实现
/// </summary>
public class DepositRequestRepository : IDepositRequestRepository
{
    private readonly AppDbContext _context;

    public DepositRequestRepository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<DepositRequest?> GetByIdAsync(Guid requestId)
    {
        return await _context.DepositRequests
            .FirstOrDefaultAsync(d => d.Id == requestId);
    }

    public async Task AddAsync(DepositRequest request)
    {
        await _context.DepositRequests.AddAsync(request);
    }

    public async Task UpdateAsync(DepositRequest request)
    {
        _context.DepositRequests.Update(request);
        await Task.CompletedTask;
    }

    public async Task<IReadOnlyList<DepositRequest>> GetByStatusAsync(DepositStatus status, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        
        return await _context.DepositRequests
            .Where(d => d.Status == status)
            .OrderByDescending(d => d.CreatedAt)
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }

    public async Task<IReadOnlyList<DepositRequest>> GetByUserIdAsync(Guid userId, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        
        return await _context.DepositRequests
            .Where(d => d.UserId == userId)
            .OrderByDescending(d => d.CreatedAt)
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }
}
