// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence.Repositories;

/// <summary>
/// 游戏订单仓储实现
/// </summary>
public class GameOrderRepository : IOrderRepository
{
    private readonly AppDbContext _context;

    public GameOrderRepository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<GameOrder?> GetByIdAsync(Guid orderId)
    {
        return await _context.GameOrders
            .FirstOrDefaultAsync(o => o.Id == orderId);
    }

    public async Task<GameOrder?> GetByInternalOrderIdAsync(string internalOrderId)
    {
        return await _context.GameOrders
            .FirstOrDefaultAsync(o => o.InternalOrderId == internalOrderId);
    }

    public async Task<GameOrder?> GetByExternalOrderIdAsync(string externalOrderId)
    {
        return await _context.GameOrders
            .FirstOrDefaultAsync(o => o.ExternalOrderId == externalOrderId);
    }

    public async Task AddAsync(GameOrder order)
    {
        await _context.GameOrders.AddAsync(order);
    }

    public async Task UpdateAsync(GameOrder order)
    {
        _context.GameOrders.Update(order);
        await Task.CompletedTask;
    }

    /// <summary>
    /// 获取超过指定时间的 Pending 状态订单（用于恢复任务）
    /// </summary>
    public async Task<IReadOnlyList<GameOrder>> GetPendingOrdersAsync(TimeSpan olderThan)
    {
        var cutoffTime = DateTime.Now.Subtract(olderThan);
        
        return await _context.GameOrders
            .Where(o => o.Status == OrderStatus.Pending && o.CreatedAt < cutoffTime)
            .OrderBy(o => o.CreatedAt)
            .ToListAsync();
    }

    /// <summary>
    /// 获取超过指定时间的 Confirmed 状态订单（用于轮询任务）
    /// </summary>
    public async Task<IReadOnlyList<GameOrder>> GetConfirmedOrdersAsync(TimeSpan olderThan)
    {
        var cutoffTime = DateTime.Now.Subtract(olderThan);
        
        return await _context.GameOrders
            .Where(o => o.Status == OrderStatus.Confirmed && o.CreatedAt < cutoffTime)
            .OrderBy(o => o.CreatedAt)
            .ToListAsync();
    }

    public async Task<IReadOnlyList<GameOrder>> GetByUserIdAsync(Guid userId, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        
        return await _context.GameOrders
            .Where(o => o.UserId == userId)
            .OrderByDescending(o => o.CreatedAt)
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }

    /// <summary>
    /// 检查用户是否有进行中的订单（Pending 或 Confirmed）
    /// </summary>
    public async Task<bool> HasActiveOrderAsync(Guid userId)
    {
        return await _context.GameOrders
            .AnyAsync(o => o.UserId == userId && 
                          (o.Status == OrderStatus.Pending || o.Status == OrderStatus.Confirmed));
    }
}
