// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence.Repositories;

/// <summary>
/// 用户银行卡仓储实现
/// </summary>
public class UserBankCardRepository : IUserBankCardRepository
{
    private readonly AppDbContext _context;

    public UserBankCardRepository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<UserBankCard?> GetByIdAsync(Guid cardId)
    {
        return await _context.UserBankCards
            .FirstOrDefaultAsync(c => c.Id == cardId);
    }

    public async Task<IReadOnlyList<UserBankCard>> GetByUserIdAsync(Guid userId)
    {
        return await _context.UserBankCards
            .Where(c => c.UserId == userId)
            .OrderByDescending(c => c.IsDefault)
            .ThenByDescending(c => c.CreatedAt)
            .ToListAsync();
    }

    public async Task AddAsync(UserBankCard card)
    {
        await _context.UserBankCards.AddAsync(card);
    }

    public async Task UpdateAsync(UserBankCard card)
    {
        _context.UserBankCards.Update(card);
        await Task.CompletedTask;
    }

    public async Task DeleteAsync(Guid cardId)
    {
        var card = await _context.UserBankCards.FindAsync(cardId);
        if (card != null)
        {
            _context.UserBankCards.Remove(card);
        }
        await Task.CompletedTask;
    }

    public async Task<int> GetCountByUserIdAsync(Guid userId)
    {
        return await _context.UserBankCards
            .CountAsync(c => c.UserId == userId);
    }
}
