// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence.Repositories;

/// <summary>
/// 用户资料仓储实现
/// </summary>
public class UserProfileRepository : IUserProfileRepository
{
    private readonly AppDbContext _context;

    public UserProfileRepository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<UserProfile?> GetByIdAsync(Guid userId)
    {
        return await _context.UserProfiles
            .FirstOrDefaultAsync(p => p.UserId == userId);
    }

    public async Task AddAsync(UserProfile profile)
    {
        await _context.UserProfiles.AddAsync(profile);
    }

    public async Task UpdateAsync(UserProfile profile)
    {
        _context.UserProfiles.Update(profile);
        await Task.CompletedTask;
    }

    public async Task<IReadOnlyList<UserProfile>> GetFilteredAsync(string? filter, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        var query = _context.UserProfiles.AsQueryable();

        if (!string.IsNullOrWhiteSpace(filter))
        {
            query = query.Where(p => p.Username.Contains(filter));
        }

        return await query
            .OrderByDescending(p => p.CreatedAt)
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }

    public async Task<IReadOnlyList<UserProfile>> GetByAgentIdAsync(Guid agentId, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        
        // TODO: 当 Agent 关系实现后，这里需要关联查询
        // 目前返回空列表
        return await _context.UserProfiles
            .Where(p => p.UserId == Guid.Empty) // 暂时返回空
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }
}
