// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence.Repositories;

/// <summary>
/// 厂商玩家映射仓储实现
/// </summary>
public class VendorPlayerMappingRepository : IVendorPlayerMappingRepository
{
    private readonly AppDbContext _context;

    public VendorPlayerMappingRepository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<VendorPlayerMapping?> GetAsync(Guid userId, string vendorCode)
    {
        return await _context.VendorPlayerMappings
            .FirstOrDefaultAsync(m => m.UserId == userId && m.VendorCode == vendorCode);
    }

    public async Task AddAsync(VendorPlayerMapping mapping)
    {
        await _context.VendorPlayerMappings.AddAsync(mapping);
    }

    public async Task UpdateAsync(VendorPlayerMapping mapping)
    {
        _context.VendorPlayerMappings.Update(mapping);
        await Task.CompletedTask;
    }
}
