// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence.Repositories;

/// <summary>
/// 钱包仓储实现（CAS 乐观锁并发控制）
/// </summary>
public class WalletRepository : IWalletRepository
{
    private readonly AppDbContext _context;

    public WalletRepository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<Wallet?> GetByUserIdAsync(Guid userId)
    {
        return await _context.Wallets
            .FirstOrDefaultAsync(w => w.UserId == userId);
    }

    public async Task<Wallet?> GetByIdAsync(Guid walletId)
    {
        return await _context.Wallets
            .FirstOrDefaultAsync(w => w.Id == walletId);
    }

    public async Task AddAsync(Wallet wallet)
    {
        await _context.Wallets.AddAsync(wallet);
    }

    /// <summary>
    /// CAS 更新钱包（乐观锁）
    /// 使用原生 SQL 确保版本号原子性检查
    /// </summary>
    public async Task<bool> UpdateWithCasAsync(Wallet wallet, int expectedVersion)
    {
        // 使用原生 SQL 执行 CAS 更新
        // 只有当 Version == expectedVersion 时才更新
        var affectedRows = await _context.Database.ExecuteSqlRawAsync(
            @"
            UPDATE ""Wallets""
            SET ""Balance"" = {0},
                ""FrozenBalance"" = {1},
                ""Version"" = {2},
                ""UpdatedAt"" = {3}
            WHERE ""Id"" = {4} AND ""Version"" = {5}",
            wallet.Balance,
            wallet.FrozenBalance,
            wallet.Version,
            wallet.UpdatedAt,
            wallet.Id,
            expectedVersion);

        return affectedRows > 0;
    }

    public async Task AddTransactionAsync(WalletTransaction transaction)
    {
        await _context.WalletTransactions.AddAsync(transaction);
    }

    public async Task<IReadOnlyList<WalletTransaction>> GetTransactionsAsync(Guid walletId, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        
        return await _context.WalletTransactions
            .Where(t => t.WalletId == walletId)
            .OrderByDescending(t => t.CreatedAt)
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }

    /// <summary>
    /// 获取钱包流水总和（用于一致性校验）
    /// </summary>
    public async Task<decimal> GetTransactionsSumAsync(Guid walletId)
    {
        var sum = await _context.WalletTransactions
            .Where(t => t.WalletId == walletId)
            .SumAsync(t => t.Amount);

        return sum;
    }
}
