// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace GamePlatform.Infrastructure.Persistence.Repositories;

/// <summary>
/// 提现申请仓储实现
/// </summary>
public class WithdrawRequestRepository : IWithdrawRequestRepository
{
    private readonly AppDbContext _context;

    public WithdrawRequestRepository(AppDbContext context)
    {
        _context = context;
    }

    public async Task<WithdrawRequest?> GetByIdAsync(Guid requestId)
    {
        return await _context.WithdrawRequests
            .FirstOrDefaultAsync(w => w.Id == requestId);
    }

    public async Task AddAsync(WithdrawRequest request)
    {
        await _context.WithdrawRequests.AddAsync(request);
    }

    public async Task UpdateAsync(WithdrawRequest request)
    {
        _context.WithdrawRequests.Update(request);
        await Task.CompletedTask;
    }

    public async Task<IReadOnlyList<WithdrawRequest>> GetByStatusAsync(WithdrawStatus status, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        
        return await _context.WithdrawRequests
            .Where(w => w.Status == status)
            .OrderByDescending(w => w.CreatedAt)
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }

    public async Task<IReadOnlyList<WithdrawRequest>> GetByUserIdAsync(Guid userId, int page, int pageSize)
    {
        var skip = (page - 1) * pageSize;
        
        return await _context.WithdrawRequests
            .Where(w => w.UserId == userId)
            .OrderByDescending(w => w.CreatedAt)
            .Skip(skip)
            .Take(pageSize)
            .ToListAsync();
    }
}
