// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Domain.Exceptions;

/// <summary>
/// 领域层基础异常
/// </summary>
public class DomainException : Exception
{
    public DomainException(string message) : base(message)
    {
    }

    public DomainException(string message, Exception innerException) : base(message, innerException)
    {
    }
}
