// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Domain.Exceptions;

/// <summary>
/// 余额不足异常
/// </summary>
public class InsufficientBalanceException : DomainException
{
    public decimal AvailableBalance { get; }
    public decimal RequestedAmount { get; }

    public InsufficientBalanceException(decimal availableBalance, decimal requestedAmount)
        : base($"Insufficient balance. Available: {availableBalance}, Requested: {requestedAmount}")
    {
        AvailableBalance = availableBalance;
        RequestedAmount = requestedAmount;
    }
}
