// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;

namespace GamePlatform.Domain.Exceptions;

/// <summary>
/// 非法状态流转异常
/// </summary>
public class InvalidStateTransitionException : DomainException
{
    public string FromStatus { get; }
    public string ToStatus { get; }

    public InvalidStateTransitionException(string fromStatus, string toStatus)
        : base($"Invalid state transition from {fromStatus} to {toStatus}.")
    {
        FromStatus = fromStatus;
        ToStatus = toStatus;
    }
}
