// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;

using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Exceptions;

/// <summary>
/// 非法状态流转异常（充值)
/// </summary>
public class InvalidDepositStateTransitionException : DomainException
{
    public string FromStatus { get; }
    public string ToStatus { get; }

    public InvalidDepositStateTransitionException(string fromStatus, string toStatus)
        : base($"Invalid state transition from {fromStatus} to {toStatus}.")
    {
        FromStatus = fromStatus;
        ToStatus = toStatus;
    }
}
