// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;

namespace GamePlatform.Domain.Exceptions;

/// <summary>
/// 銶态机异常基类（使用字符串类型）
/// </summary>
public class StateMachineException : DomainException
{
    public string FromStatus { get; }
    public string ToStatus { get; }

    public StateMachineException(string fromStatus, string toStatus)
        : base($"Invalid state transition from {fromStatus} to {toStatus}.")
    {
        FromStatus = fromStatus;
        ToStatus = toStatus;
    }

}
