// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GamePlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// DepositRequest 实体配置
/// </summary>
public class DepositRequestConfiguration : IEntityTypeConfiguration<DepositRequest>
{
    public void Configure(EntityTypeBuilder<DepositRequest> builder)
    {
        builder.ToTable("DepositRequests");

        builder.HasKey(d => d.Id);

        builder.Property(d => d.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(d => d.UserId)
            .IsRequired();

        builder.Property(d => d.InternalOrderId)
            .IsRequired()
            .HasMaxLength(64);

        builder.Property(d => d.ExternalOrderId)
            .HasMaxLength(64);

        builder.Property(d => d.Amount)
            .IsRequired()
            .HasPrecision(18, 2);

        builder.Property(d => d.PaymentMethod)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(d => d.Status)
            .IsRequired()
            .HasConversion(
                v => (int)v,
                v => (DepositStatus)v);

        builder.Property(d => d.ErrorMessage)
            .HasMaxLength(1000);

        builder.Property(d => d.CreatedAt)
            .IsRequired();

        builder.Property(d => d.UpdatedAt)
            .IsRequired();

        // Indexes
        builder.HasIndex(d => d.UserId);
        builder.HasIndex(d => d.Status);
        builder.HasIndex(d => d.InternalOrderId).IsUnique();
        builder.HasIndex(d => d.ExternalOrderId).IsUnique();

        // Relationships
        builder.HasOne<UserProfile>()
            .WithMany()
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
