// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GamePlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// GameOrder 实体配置
/// </summary>
public class GameOrderConfiguration : IEntityTypeConfiguration<GameOrder>
{
    public void Configure(EntityTypeBuilder<GameOrder> builder)
    {
        builder.ToTable("GameOrders");

        builder.HasKey(o => o.Id);

        builder.Property(o => o.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(o => o.UserId)
            .IsRequired();

        builder.Property(o => o.VendorCode)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(o => o.PlatType)
            .IsRequired()
            .HasMaxLength(20);

        builder.Property(o => o.GameCode)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(o => o.InternalOrderId)
            .IsRequired()
            .HasMaxLength(32);

        builder.Property(o => o.ExternalOrderId)
            .HasMaxLength(64);

        builder.Property(o => o.TransferInAmount)
            .IsRequired()
            .HasPrecision(18, 2);

        builder.Property(o => o.TransferOutAmount)
            .HasPrecision(18, 2);

        builder.Property(o => o.Status)
            .IsRequired()
            .HasConversion(
                v => (int)v,
                v => (OrderStatus)v);

        builder.Property(o => o.GameUrl)
            .HasMaxLength(2000);

        builder.Property(o => o.ErrorMessage)
            .HasMaxLength(1000);

        builder.Property(o => o.CancelReason)
            .HasMaxLength(1000);

        builder.Property(o => o.CreatedAt)
            .IsRequired();

        builder.Property(o => o.UpdatedAt)
            .IsRequired();

        // Indexes
        builder.HasIndex(o => o.UserId);
        builder.HasIndex(o => o.Status);
        builder.HasIndex(o => o.VendorCode);
        builder.HasIndex(o => o.CreatedAt);
        builder.HasIndex(o => o.InternalOrderId).IsUnique();
        builder.HasIndex(o => o.ExternalOrderId).IsUnique();

        // Relationships
        builder.HasOne<UserProfile>()
            .WithMany()
            .HasForeignKey(o => o.UserId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
