// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GamePlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// UserBankCard 实体配置
/// </summary>
public class UserBankCardConfiguration : IEntityTypeConfiguration<UserBankCard>
{
    public void Configure(EntityTypeBuilder<UserBankCard> builder)
    {
        builder.ToTable("UserBankCards");

        builder.HasKey(c => c.Id);

        builder.Property(c => c.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(c => c.UserId)
            .IsRequired();

        builder.Property(c => c.BankName)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(c => c.BankCardNumber)
            .IsRequired()
            .HasMaxLength(19);

        builder.Property(c => c.AccountName)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(c => c.IsDefault)
            .IsRequired();

        builder.Property(c => c.CreatedAt)
            .IsRequired();

        builder.Property(c => c.UpdatedAt)
            .IsRequired();

        // Indexes
        builder.HasIndex(c => c.UserId);
        builder.HasIndex(c => new { c.UserId, c.BankCardNumber }).IsUnique();

        // Relationships
        builder.HasOne<UserProfile>()
            .WithMany()
            .HasForeignKey(c => c.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
