// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GamePlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// VendorPlayerMapping 实体配置
/// </summary>
public class VendorPlayerMappingConfiguration : IEntityTypeConfiguration<VendorPlayerMapping>
{
    public void Configure(EntityTypeBuilder<VendorPlayerMapping> builder)
    {
        builder.ToTable("VendorPlayerMappings");

        builder.HasKey(m => m.Id);

        builder.Property(m => m.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(m => m.UserId)
            .IsRequired();

        builder.Property(m => m.VendorCode)
            .IsRequired()
            .HasMaxLength(50);

        builder.Property(m => m.VendorPlayerId)
            .IsRequired()
            .HasMaxLength(20);

        builder.Property(m => m.CreatedAt)
            .IsRequired();

        builder.Property(m => m.UpdatedAt)
            .IsRequired();

        // Indexes
        builder.HasIndex(m => new { m.UserId, m.VendorCode }).IsUnique();
        builder.HasIndex(m => new { m.VendorCode, m.VendorPlayerId }).IsUnique();

        // Relationships
        builder.HasOne<UserProfile>()
            .WithMany()
            .HasForeignKey(m => m.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
