// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GamePlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// Wallet 实体配置
/// </summary>
public class WalletConfiguration : IEntityTypeConfiguration<Wallet>
{
    public void Configure(EntityTypeBuilder<Wallet> builder)
    {
        builder.ToTable("Wallets", t =>
        {
            t.HasCheckConstraint("CK_Wallets_Balance_NonNegative", "\"Balance\" >= 0");
            t.HasCheckConstraint("CK_Wallets_FrozenBalance_NonNegative", "\"FrozenBalance\" >= 0");
            t.HasCheckConstraint("CK_Wallets_FrozenBalance_LTE_Balance", "\"FrozenBalance\" <= \"Balance\"");
        });

        builder.HasKey(w => w.Id);

        builder.Property(w => w.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(w => w.UserId)
            .IsRequired();

        builder.Property(w => w.Balance)
            .IsRequired()
            .HasPrecision(18, 2)
            .HasDefaultValue(0m);

        builder.Property(w => w.FrozenBalance)
            .IsRequired()
            .HasPrecision(18, 2)
            .HasDefaultValue(0m);

        builder.Property(w => w.Version)
            .IsRequired()
            .HasDefaultValue(0)
            .IsConcurrencyToken();

        builder.Property(w => w.CreatedAt)
            .IsRequired();

        builder.Property(w => w.UpdatedAt)
            .IsRequired();

        // Indexes
        builder.HasIndex(w => w.UserId).IsUnique();
    }
}
