// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GamePlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// WalletTransaction 实体配置
/// </summary>
public class WalletTransactionConfiguration : IEntityTypeConfiguration<WalletTransaction>
{
    public void Configure(EntityTypeBuilder<WalletTransaction> builder)
    {
        builder.ToTable("WalletTransactions");

        builder.HasKey(t => t.Id);

        builder.Property(t => t.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(t => t.WalletId)
            .IsRequired();

        builder.Property(t => t.Type)
            .IsRequired()
            .HasConversion(
                v => (int)v,
                v => (TransactionType)v);

        builder.Property(t => t.Amount)
            .IsRequired()
            .HasPrecision(18, 2);

        builder.Property(t => t.BalanceBefore)
            .IsRequired()
            .HasPrecision(18, 2);

        builder.Property(t => t.BalanceAfter)
            .IsRequired()
            .HasPrecision(18, 2);

        builder.Property(t => t.Description)
            .IsRequired()
            .HasMaxLength(500);

        builder.Property(t => t.OrderId)
            .IsRequired(false);

        builder.Property(t => t.InternalOrderId)
            .HasMaxLength(64);

        builder.Property(t => t.CreatedAt)
            .IsRequired();

        // Indexes
        builder.HasIndex(t => t.WalletId);
        builder.HasIndex(t => t.OrderId);
        builder.HasIndex(t => t.CreatedAt);

        // Idempotency index
        builder.HasIndex(t => new { t.WalletId, t.InternalOrderId, t.Type })
            .HasFilter("\"InternalOrderId\" IS NOT NULL")
            .IsUnique();

        // Relationships
        builder.HasOne<Wallet>()
            .WithMany()
            .HasForeignKey(t => t.WalletId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
