// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GamePlatform.Infrastructure.Persistence.Configurations;

/// <summary>
/// WithdrawRequest 实体配置
/// </summary>
public class WithdrawRequestConfiguration : IEntityTypeConfiguration<WithdrawRequest>
{
    public void Configure(EntityTypeBuilder<WithdrawRequest> builder)
    {
        builder.ToTable("WithdrawRequests");

        builder.HasKey(w => w.Id);

        builder.Property(w => w.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(w => w.UserId)
            .IsRequired();

        builder.Property(w => w.InternalOrderId)
            .IsRequired()
            .HasMaxLength(64);

        builder.Property(w => w.ExternalOrderId)
            .HasMaxLength(64);

        builder.Property(w => w.Amount)
            .IsRequired()
            .HasPrecision(18, 2);

        builder.Property(w => w.BankCardId)
            .IsRequired();

        builder.Property(w => w.Status)
            .IsRequired()
            .HasConversion(
                v => (int)v,
                v => (WithdrawStatus)v);

        builder.Property(w => w.RejectionReason)
            .HasMaxLength(500);

        builder.Property(w => w.CreatedAt)
            .IsRequired();

        builder.Property(w => w.UpdatedAt)
            .IsRequired();

        // Indexes
        builder.HasIndex(w => w.UserId);
        builder.HasIndex(w => w.Status);
        builder.HasIndex(w => w.InternalOrderId).IsUnique();
        builder.HasIndex(w => w.ExternalOrderId).IsUnique();

        // Relationships
        builder.HasOne<UserProfile>()
            .WithMany()
            .HasForeignKey(w => w.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne<UserBankCard>()
            .WithMany()
            .HasForeignKey(w => w.BankCardId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
