// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using Xunit;

namespace GamePlatform.Domain.Tests.Entities;

public class DepositRequestTests
{
    private readonly Guid _testUserId = Guid.NewGuid();
    private readonly string _testInternalOrderId = Guid.NewGuid().ToString("N");
    private readonly decimal _testAmount = 100m;
    private readonly string _testPaymentMethod = "BankTransfer";
    private readonly DateTime _testNow = new(2026, 3, 10, 12, 0, 0);

    [Fact]
    public void Create_WithValidParameters_ShouldInitializeCorrectly()
    {
        // Act
        var request = DepositRequest.Create(
            _testUserId,
            _testInternalOrderId,
            _testAmount,
            _testPaymentMethod,
            _testNow);

        // Assert
        request.Id.Should().NotBe(Guid.Empty);
        request.UserId.Should().Be(_testUserId);
        request.InternalOrderId.Should().Be(_testInternalOrderId);
        request.ExternalOrderId.Should().BeNull();
        request.Amount.Should().Be(_testAmount);
        request.PaymentMethod.Should().Be(_testPaymentMethod);
        request.Status.Should().Be(DepositStatus.Pending);
        request.CreatedAt.Should().Be(_testNow);
        request.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Create_WithEmptyUserId_ShouldThrowDomainException()
    {
        // Act
        var act = () => DepositRequest.Create(
            Guid.Empty,
            _testInternalOrderId,
            _testAmount,
            _testPaymentMethod,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("UserId cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyInternalOrderId_ShouldThrowDomainException()
    {
        // Act
        var act = () => DepositRequest.Create(
            _testUserId,
            "",
            _testAmount,
            _testPaymentMethod,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("InternalOrderId cannot be empty*");
    }

    [Fact]
    public void Create_WithZeroAmount_ShouldThrowDomainException()
    {
        // Act
        var act = () => DepositRequest.Create(
            _testUserId,
            _testInternalOrderId,
            0m,
            _testPaymentMethod,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("Amount must be positive*");
    }

    [Fact]
    public void Create_WithNegativeAmount_ShouldThrowDomainException()
    {
        // Act
        var act = () => DepositRequest.Create(
            _testUserId,
            _testInternalOrderId,
            -100m,
            _testPaymentMethod,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("Amount must be positive*");
    }

    [Fact]
    public void Confirm_WithValidParameters_ShouldUpdateStatusAndExternalOrderId()
    {
        // Arrange
        var request = CreatePendingDeposit();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Confirm("external-order-123", newNow);

        // Assert
        request.Status.Should().Be(DepositStatus.Confirmed);
        request.ExternalOrderId.Should().Be("external-order-123");
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Confirm_FromNonPendingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreatePendingDeposit();
        request.Confirm("external-order-123", _testNow);

        // Act
        var act = () => request.Confirm("external-order-456", _testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    [Fact]
    public void Confirm_WithEmptyExternalOrderId_ShouldThrowDomainException()
    {
        // Arrange
        var request = CreatePendingDeposit();

        // Act
        var act = () => request.Confirm("", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("ExternalOrderId cannot be empty*");
    }

    [Fact]
    public void Settle_FromConfirmedStatus_ShouldUpdateStatus()
    {
        // Arrange
        var request = CreateConfirmedDeposit();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Settle(newNow);

        // Assert
        request.Status.Should().Be(DepositStatus.Settled);
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Settle_FromNonConfirmedStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreatePendingDeposit();

        // Act
        var act = () => request.Settle(_testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    [Fact]
    public void Cancel_FromPendingStatus_ShouldUpdateStatus()
    {
        // Arrange
        var request = CreatePendingDeposit();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Cancel(newNow);

        // Assert
        request.Status.Should().Be(DepositStatus.Cancelled);
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Cancel_FromNonPendingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreateConfirmedDeposit();

        // Act
        var act = () => request.Cancel(_testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    [Fact]
    public void Fail_FromPendingStatus_ShouldUpdateStatus()
    {
        // Arrange
        var request = CreatePendingDeposit();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Fail("Payment gateway error", newNow);

        // Assert
        request.Status.Should().Be(DepositStatus.Failed);
        request.ErrorMessage.Should().Be("Payment gateway error");
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Fail_FromNonPendingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreateConfirmedDeposit();

        // Act
        var act = () => request.Fail("Error", _testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    #region Helper Methods

    private DepositRequest CreatePendingDeposit()
    {
        return DepositRequest.Create(
            _testUserId,
            _testInternalOrderId,
            _testAmount,
            _testPaymentMethod,
            _testNow);
    }

    private DepositRequest CreateConfirmedDeposit()
    {
        var request = CreatePendingDeposit();
        request.Confirm("external-order-123", _testNow);
        return request;
    }

    #endregion
}
