// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Rules;
using Xunit;

namespace GamePlatform.Domain.Tests.Entities;

public class GameOrderTests
{
    private readonly Guid _testUserId = Guid.NewGuid();
    private readonly string _testVendorCode = "test-vendor";
    private readonly string _testPlatType = "ag";
    private readonly string _testGameCode = "test-game";
    private readonly DateTime _testNow = DateTime.Now;

    #region Create Tests

    [Fact]
    public void Create_WithValidParameters_ShouldInitializeCorrectly()
    {
        // Arrange
        var internalOrderId = Guid.NewGuid().ToString("N");

        // Act
        var order = GameOrder.Create(
            _testUserId,
            _testVendorCode,
            _testPlatType,
            _testGameCode,
            internalOrderId,
            100m,
            _testNow);

        // Assert
        order.UserId.Should().Be(_testUserId);
        order.VendorCode.Should().Be(_testVendorCode);
        order.PlatType.Should().Be(_testPlatType);
        order.GameCode.Should().Be(_testGameCode);
        order.InternalOrderId.Should().Be(internalOrderId);
        order.TransferInAmount.Should().Be(100m);
        order.Status.Should().Be(OrderStatus.Pending);
        order.TransferOutAmount.Should().BeNull();
        order.ExternalOrderId.Should().BeNull();
        order.GameUrl.Should().BeNull();
        order.ErrorMessage.Should().BeNull();
        order.CancelReason.Should().BeNull();
    }

    [Fact]
    public void Create_WithEmptyUserId_ShouldThrowDomainException()
    {
        // Arrange
        var internalOrderId = Guid.NewGuid().ToString("N");

        // Act
        var act = () => GameOrder.Create(
            Guid.Empty,
            _testVendorCode,
            _testPlatType,
            _testGameCode,
            internalOrderId,
            100m,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("UserId cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyVendorCode_ShouldThrowDomainException()
    {
        // Arrange
        var internalOrderId = Guid.NewGuid().ToString("N");

        // Act
        var act = () => GameOrder.Create(
                _testUserId,
                "",
                _testPlatType,
                _testGameCode,
                internalOrderId,
                100m,
                _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("VendorCode cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyPlatType_ShouldThrowDomainException()
    {
        // Arrange
        var internalOrderId = Guid.NewGuid().ToString("N");

        // Act
        var act = () => GameOrder.Create(
                _testUserId,
                _testVendorCode,
                "",
                _testGameCode,
                internalOrderId,
                100m,
                _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("PlatType cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyGameCode_ShouldThrowDomainException()
    {
        // Arrange
        var internalOrderId = Guid.NewGuid().ToString("N");

        // Act
        var act = () => GameOrder.Create(
                _testUserId,
                _testVendorCode,
                _testPlatType,
                "",
                internalOrderId,
                100m,
                _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("GameCode cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyInternalOrderId_ShouldThrowDomainException()
    {
        // Act
        var act = () => GameOrder.Create(
                _testUserId,
                _testVendorCode,
                _testPlatType,
                _testGameCode,
                "",
                100m,
                _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("InternalOrderId cannot be empty*");
    }

    [Fact]
    public void Create_WithNegativeTransferInAmount_ShouldThrowDomainException()
    {
        // Arrange
        var internalOrderId = Guid.NewGuid().ToString("N");

        // Act
        var act = () => GameOrder.Create(
                _testUserId,
                _testVendorCode,
                _testPlatType,
                _testGameCode,
                internalOrderId,
                -100m,
                _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("TransferInAmount cannot be negative*");
    }

    #endregion

    #region Confirm Tests

    [Fact]
    public void Confirm_WithValidParameters_ShouldSetExternalOrderIdAndGameUrl()
    {
        // Arrange
        var order = CreatePendingOrder();

        // Act
        order.Confirm("external-order-123", "https://game.url", _testNow);

        // Assert
        order.ExternalOrderId.Should().Be("external-order-123");
        order.GameUrl.Should().Be("https://game.url");
        order.Status.Should().Be(OrderStatus.Confirmed);
        order.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Confirm_WithEmptyExternalOrderId_ShouldThrowDomainException()
    {
        // Arrange
        var order = CreatePendingOrder();

        // Act
        var act = () => order.Confirm("", "https://game.url", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("ExternalOrderId cannot be empty*");
    }

    [Fact]
    public void Confirm_WithEmptyGameUrl_ShouldThrowDomainException()
    {
        // Arrange
        var order = CreatePendingOrder();

        // Act
        var act = () => order.Confirm("external-order-123", "", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("GameUrl cannot be empty*");
    }

    [Fact]
    public void Confirm_FromNonPendingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var order = CreateSettledOrder();

        // Act
        var act = () => order.Confirm("external-order-123", "https://game.url", _testNow);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    #endregion

    #region Settle Tests

    [Fact]
    public void Settle_WithValidAmount_ShouldSetTransferOutAmountAndStatus()
    {
        // Arrange
        var order = CreateConfirmedOrder();

        // Act
        order.Settle(50m, _testNow);

        // Assert
        order.TransferOutAmount.Should().Be(50m);
        order.Status.Should().Be(OrderStatus.Settled);
        order.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Settle_WithZeroOrNegativeAmount_ShouldThrowDomainException()
    {
        // Arrange
        var order = CreateConfirmedOrder();

        // Act
        var act = () => order.Settle(0m, _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("TransferOutAmount must be greater than zero*");
    }

    [Fact]
    public void Settle_FromNonConfirmedStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var order = CreatePendingOrder();

        // Act
        var act = () => order.Settle(50m, _testNow);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    #endregion

    #region Cancel Tests

    [Fact]
    public void Cancel_WithReason_ShouldSetCancelReason()
    {
        // Arrange
        var order = CreateConfirmedOrder();

        // Act
        order.Cancel("User requested to cancel", _testNow);

        // Assert
        order.CancelReason.Should().Be("User requested to cancel");
        order.Status.Should().Be(OrderStatus.Cancelled);
        order.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Cancel_FromNonConfirmedStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var order = CreatePendingOrder();

        // Act
        var act = () => order.Cancel("User requested to cancel", _testNow);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    #endregion

    #region Fail Tests

    [Fact]
    public void Fail_WithMessage_ShouldSetErrorMessage()
    {
        // Arrange
        var order = CreatePendingOrder(); // Fail can only be called from Pending status

        // Act
        order.Fail("Vendor API timeout", _testNow);

        // Assert
        order.ErrorMessage.Should().Be("Vendor API timeout");
        order.Status.Should().Be(OrderStatus.Failed);
        order.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Fail_WithEmptyMessage_ShouldThrowDomainException()
    {
        // Arrange
        var order = CreatePendingOrder(); // Fail can only be called from Pending status

        // Act
        var act = () => order.Fail("", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("ErrorMessage cannot be empty*");
    }

    [Fact]
    public void Fail_FromNonPendingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange - Fail can only be called from Pending, not from Confirmed
        var order = CreateConfirmedOrder();

        // Act
        var act = () => order.Fail("Error occurred", _testNow);

        // Assert
        act.Should().Throw<InvalidStateTransitionException>();
    }

    #endregion

    #region Helper Methods

    private GameOrder CreatePendingOrder()
    {
        return GameOrder.Create(
            _testUserId,
            _testVendorCode,
            _testPlatType,
            _testGameCode,
            Guid.NewGuid().ToString("N"),
            100m,
            _testNow);
    }

    private GameOrder CreateConfirmedOrder()
    {
        var order = CreatePendingOrder();
        order.Confirm("external-order-123", "https://game.url", _testNow);
        return order;
    }

    private GameOrder CreateSettledOrder()
    {
        var order = CreateConfirmedOrder();
        order.Settle(50m, _testNow);
        return order;
    }

    #endregion
}
