// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Exceptions;
using Xunit;

namespace GamePlatform.Domain.Tests.Entities;

public class UserBankCardTests
{
    private readonly Guid _testUserId = Guid.NewGuid();
    private readonly string _testBankName = "中国工商银行";
    private readonly string _testBankCardNumber = "6222021234567890123";
    private readonly string _testAccountName = "张三";
    private readonly DateTime _testNow = new(2026, 3, 10, 12, 0, 0);

    [Fact]
    public void Create_WithValidParameters_ShouldInitializeCorrectly()
    {
        // Act
        var card = UserBankCard.Create(
            _testUserId,
            _testBankName,
            _testBankCardNumber,
            _testAccountName,
            _testNow);

        // Assert
        card.Id.Should().NotBe(Guid.Empty);
        card.UserId.Should().Be(_testUserId);
        card.BankName.Should().Be(_testBankName);
        card.BankCardNumber.Should().Be(_testBankCardNumber);
        card.AccountName.Should().Be(_testAccountName);
        card.IsDefault.Should().BeFalse();
        card.CreatedAt.Should().Be(_testNow);
        card.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Create_WithEmptyUserId_ShouldThrowDomainException()
    {
        // Act
        var act = () => UserBankCard.Create(
            Guid.Empty,
            _testBankName,
            _testBankCardNumber,
            _testAccountName,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("UserId cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyBankName_ShouldThrowDomainException()
    {
        // Act
        var act = () => UserBankCard.Create(
            _testUserId,
            "",
            _testBankCardNumber,
            _testAccountName,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("BankName cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyBankCardNumber_ShouldThrowDomainException()
    {
        // Act
        var act = () => UserBankCard.Create(
            _testUserId,
            _testBankName,
            "",
            _testAccountName,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("BankCardNumber cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyAccountName_ShouldThrowDomainException()
    {
        // Act
        var act = () => UserBankCard.Create(
            _testUserId,
            _testBankName,
            _testBankCardNumber,
            "",
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("AccountName cannot be empty*");
    }

    [Fact]
    public void SetAsDefault_ShouldSetIsDefaultToTrue()
    {
        // Arrange
        var card = CreateUserBankCard();
        var newNow = _testNow.AddHours(1);

        // Act
        card.SetAsDefault(newNow);

        // Assert
        card.IsDefault.Should().BeTrue();
        card.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void UnsetAsDefault_ShouldSetIsDefaultToFalse()
    {
        // Arrange
        var card = CreateUserBankCard();
        card.SetAsDefault(_testNow);
        var newNow = _testNow.AddHours(1);

        // Act
        card.UnsetAsDefault(newNow);

        // Assert
        card.IsDefault.Should().BeFalse();
        card.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void GetMaskedCardNumber_ShouldReturnMaskedNumber()
    {
        // Arrange
        var card = UserBankCard.Create(
            _testUserId,
            _testBankName,
            "6222021234567890123",
            _testAccountName,
            _testNow);

        // Act
        var masked = card.GetMaskedCardNumber();

        // Assert
        masked.Should().Be("6222 **** **** 0123");
    }

    [Fact]
    public void GetMaskedCardNumber_WithShortNumber_ShouldReturnMaskedNumber()
    {
        // Arrange
        var card = UserBankCard.Create(
            _testUserId,
            _testBankName,
            "123456",
            _testAccountName,
            _testNow);

        // Act
        var masked = card.GetMaskedCardNumber();

        // Assert
        masked.Should().Be("123456");
    }

    #region Helper Methods

    private UserBankCard CreateUserBankCard()
    {
        return UserBankCard.Create(
            _testUserId,
            _testBankName,
            _testBankCardNumber,
            _testAccountName,
            _testNow);
    }

    #endregion
}
