// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Exceptions;
using Xunit;

namespace GamePlatform.Domain.Tests.Entities;

public class UserProfileTests
{
    private readonly Guid _testUserId = Guid.NewGuid();
    private readonly string _testUsername = "testuser";
    private readonly DateTime _testNow = new(2026, 3, 10, 12, 0, 0);

    [Fact]
    public void Create_WithValidParameters_ShouldInitializeCorrectly()
    {
        // Act
        var profile = UserProfile.Create(_testUserId, _testUsername, _testNow);

        // Assert
        profile.Id.Should().NotBe(Guid.Empty);
        profile.UserId.Should().Be(_testUserId);
        profile.Username.Should().Be(_testUsername);
        profile.AvatarUrl.Should().BeNull();
        profile.CreatedAt.Should().Be(_testNow);
        profile.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Create_WithEmptyUserId_ShouldThrowDomainException()
    {
        // Act
        var act = () => UserProfile.Create(Guid.Empty, _testUsername, _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("UserId cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyUsername_ShouldThrowDomainException()
    {
        // Act
        var act = () => UserProfile.Create(_testUserId, "", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("Username cannot be empty*");
    }

    [Fact]
    public void UpdateUsername_WithValidName_ShouldUpdateUsername()
    {
        // Arrange
        var profile = UserProfile.Create(_testUserId, _testUsername, _testNow);
        var newNow = _testNow.AddHours(1);

        // Act
        profile.UpdateUsername("newusername", newNow);

        // Assert
        profile.Username.Should().Be("newusername");
        profile.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void UpdateUsername_WithEmptyName_ShouldThrowDomainException()
    {
        // Arrange
        var profile = UserProfile.Create(_testUserId, _testUsername, _testNow);

        // Act
        var act = () => profile.UpdateUsername("", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("Username cannot be empty*");
    }

    [Fact]
    public void UpdateAvatar_WithValidUrl_ShouldUpdateAvatarUrl()
    {
        // Arrange
        var profile = UserProfile.Create(_testUserId, _testUsername, _testNow);
        var newNow = _testNow.AddHours(1);
        var avatarUrl = "https://example.com/avatar.png";

        // Act
        profile.UpdateAvatar(avatarUrl, newNow);

        // Assert
        profile.AvatarUrl.Should().Be(avatarUrl);
        profile.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void UpdateAvatar_WithNull_ShouldClearAvatarUrl()
    {
        // Arrange
        var profile = UserProfile.Create(_testUserId, _testUsername, _testNow);
        profile.UpdateAvatar("https://example.com/avatar.png", _testNow);
        var newNow = _testNow.AddHours(1);

        // Act
        profile.UpdateAvatar(null, newNow);

        // Assert
        profile.AvatarUrl.Should().BeNull();
        profile.UpdatedAt.Should().Be(newNow);
    }
}
