// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Exceptions;
using Xunit;

namespace GamePlatform.Domain.Tests.Entities;

public class VendorPlayerMappingTests
{
    private readonly Guid _testUserId = Guid.NewGuid();
    private readonly string _testVendorCode = "VENDOR001";
    private readonly string _testVendorPlayerId = "VP123456";
    private readonly DateTime _testNow = new(2026, 3, 10, 12, 0, 0);

    [Fact]
    public void Create_WithValidParameters_ShouldInitializeCorrectly()
    {
        // Act
        var mapping = VendorPlayerMapping.Create(
            _testUserId,
            _testVendorCode,
            _testVendorPlayerId,
            _testNow);

        // Assert
        mapping.Id.Should().NotBe(Guid.Empty);
        mapping.UserId.Should().Be(_testUserId);
        mapping.VendorCode.Should().Be(_testVendorCode);
        mapping.VendorPlayerId.Should().Be(_testVendorPlayerId);
        mapping.CreatedAt.Should().Be(_testNow);
        mapping.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Create_WithEmptyUserId_ShouldThrowDomainException()
    {
        // Act
        var act = () => VendorPlayerMapping.Create(
            Guid.Empty,
            _testVendorCode,
            _testVendorPlayerId,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("UserId cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyVendorCode_ShouldThrowDomainException()
    {
        // Act
        var act = () => VendorPlayerMapping.Create(
            _testUserId,
            "",
            _testVendorPlayerId,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("VendorCode cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyVendorPlayerId_ShouldThrowDomainException()
    {
        // Act
        var act = () => VendorPlayerMapping.Create(
            _testUserId,
            _testVendorCode,
            "",
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("VendorPlayerId cannot be empty*");
    }
}
