// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using Xunit;

namespace GamePlatform.Domain.Tests.Entities;

public class WalletTests
{
    private readonly Guid _testUserId = Guid.NewGuid();
    private readonly DateTime _testNow = DateTime.Now;

    #region Create Tests

    [Fact]
    public void Create_ShouldInitializeWithZeroBalance()
    {
        // Arrange & Act
        var wallet = Wallet.Create(_testUserId, _testNow);

        // Assert
        wallet.UserId.Should().Be(_testUserId);
        wallet.Balance.Should().Be(0);
        wallet.FrozenBalance.Should().Be(0);
        wallet.AvailableBalance.Should().Be(0);
        wallet.Version.Should().Be(0);
        wallet.CreatedAt.Should().Be(_testNow);
        wallet.UpdatedAt.Should().Be(_testNow);
    }

    #endregion

    #region Credit Tests

    [Fact]
    public void Credit_NormalAmount_ShouldIncreaseBalance()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        var initialVersion = wallet.Version;

        // Act
        var transaction = wallet.Credit(100m, TransactionType.Deposit, "Test deposit", _testNow);

        // Assert
        wallet.Balance.Should().Be(100m);
        wallet.Version.Should().Be(initialVersion + 1);
        wallet.UpdatedAt.Should().Be(_testNow);
        transaction.Should().NotBeNull();
        transaction.Amount.Should().Be(100m);
        transaction.BalanceBefore.Should().Be(0m);
        transaction.BalanceAfter.Should().Be(100m);
    }

    [Fact]
    public void Credit_ZeroAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);

        // Act
        var act = () => wallet.Credit(0m, TransactionType.Deposit, "Test", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*greater than zero*");
    }

    [Fact]
    public void Credit_NegativeAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);

        // Act
        var act = () => wallet.Credit(-50m, TransactionType.Deposit, "Test", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*greater than zero*");
    }

    [Fact]
    public void Credit_LargeAmount_ShouldProcessCorrectly()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        var largeAmount = 999_999_999_999.99m;

        // Act
        var transaction = wallet.Credit(largeAmount, TransactionType.Deposit, "Large deposit", _testNow);

        // Assert
        wallet.Balance.Should().Be(largeAmount);
        transaction.Amount.Should().Be(largeAmount);
    }

    [Fact]
    public void Credit_TransactionAmountShouldBePositive()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);

        // Act
        var transaction = wallet.Credit(100m, TransactionType.Deposit, "Test", _testNow);

        // Assert
        transaction.Amount.Should().BePositive();
    }

    [Fact]
    public void Credit_BalanceBeforeAndAfterCorrect()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var transaction = wallet.Credit(100m, TransactionType.Deposit, "Second", _testNow);

        // Assert
        transaction.BalanceBefore.Should().Be(500m);
        transaction.BalanceAfter.Should().Be(600m);
    }

    #endregion

    #region Debit Tests

    [Fact]
    public void Debit_NormalAmount_ShouldDecreaseBalance()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        var initialVersion = wallet.Version;

        // Act
        var transaction = wallet.Debit(100m, TransactionType.Withdrawal, "Test withdrawal", _testNow);

        // Assert
        wallet.Balance.Should().Be(400m);
        wallet.Version.Should().Be(initialVersion + 1);
        wallet.UpdatedAt.Should().Be(_testNow);
        transaction.Amount.Should().Be(-100m);
        transaction.BalanceBefore.Should().Be(500m);
        transaction.BalanceAfter.Should().Be(400m);
    }

    [Fact]
    public void Debit_InsufficientBalance_ShouldThrowInsufficientBalanceException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var act = () => wallet.Debit(600m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        act.Should().Throw<InsufficientBalanceException>();
    }

    [Fact]
    public void Debit_AmountEqualToBalance_ShouldSucceed()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var transaction = wallet.Debit(500m, TransactionType.Withdrawal, "Full withdrawal", _testNow);

        // Assert
        wallet.Balance.Should().Be(0m);
        transaction.BalanceAfter.Should().Be(0m);
    }

    [Fact]
    public void Debit_ZeroAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var act = () => wallet.Debit(0m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*greater than zero*");
    }

    [Fact]
    public void Debit_NegativeAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var act = () => wallet.Debit(-50m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*greater than zero*");
    }

    [Fact]
    public void Debit_TransactionAmountShouldBeNegative()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var transaction = wallet.Debit(100m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        transaction.Amount.Should().BeNegative();
    }

    [Fact]
    public void Debit_ChecksAvailableBalanceNotTotalBalance()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(200m, _testNow); // Balance=500, Frozen=200, Available=300

        // Act
        var act = () => wallet.Debit(400m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        act.Should().Throw<InsufficientBalanceException>();
    }

    [Fact]
    public void Debit_AvailableBalanceExactlyEnough_ShouldSucceed()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(200m, _testNow); // Balance=500, Frozen=200, Available=300

        // Act
        var transaction = wallet.Debit(300m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        wallet.Balance.Should().Be(200m);
        transaction.BalanceAfter.Should().Be(200m);
    }

    #endregion

    #region AvailableBalance Tests

    [Fact]
    public void AvailableBalance_ShouldBeBalanceMinusFrozen()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(1000m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(300m, _testNow);

        // Act & Assert
        wallet.AvailableBalance.Should().Be(700m);
        wallet.Balance.Should().Be(1000m);
        wallet.FrozenBalance.Should().Be(300m);
    }

    #endregion

    #region Freeze Tests

    [Fact]
    public void Freeze_NormalAmount_ShouldIncreaseFrozenBalance()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        var initialVersion = wallet.Version;

        // Act
        wallet.Freeze(200m, _testNow);

        // Assert
        wallet.FrozenBalance.Should().Be(200m);
        wallet.Balance.Should().Be(500m); // Balance unchanged
        wallet.Version.Should().Be(initialVersion + 1);
        wallet.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Freeze_InsufficientAvailableBalance_ShouldThrowInsufficientBalanceException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(100m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var act = () => wallet.Freeze(200m, _testNow);

        // Assert
        act.Should().Throw<InsufficientBalanceException>();
    }

    [Fact]
    public void Freeze_ZeroAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);

        // Act
        var act = () => wallet.Freeze(0m, _testNow);

        // Assert
        act.Should().Throw<DomainException>();
    }

    #endregion

    #region Unfreeze Tests

    [Fact]
    public void Unfreeze_NormalAmount_ShouldDecreaseFrozenBalance()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(200m, _testNow);
        var initialVersion = wallet.Version;

        // Act
        wallet.Unfreeze(200m, _testNow);

        // Assert
        wallet.FrozenBalance.Should().Be(0m);
        wallet.Version.Should().Be(initialVersion + 1);
        wallet.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Unfreeze_ExceedFrozenAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(100m, _testNow);

        // Act
        var act = () => wallet.Unfreeze(200m, _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*Frozen balance*");
    }

    [Fact]
    public void Unfreeze_ZeroAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(100m, _testNow);

        // Act
        var act = () => wallet.Unfreeze(0m, _testNow);

        // Assert
        act.Should().Throw<DomainException>();
    }

    #endregion

    #region ConfirmFrozenDebit Tests

    [Fact]
    public void ConfirmFrozenDebit_NormalAmount_ShouldDecreaseBothBalances()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(200m, _testNow); // Balance=500, Frozen=200
        var initialVersion = wallet.Version;

        // Act
        var transaction = wallet.ConfirmFrozenDebit(200m, TransactionType.Withdrawal, "Confirmed withdrawal", _testNow);

        // Assert
        wallet.Balance.Should().Be(300m);
        wallet.FrozenBalance.Should().Be(0m);
        wallet.Version.Should().Be(initialVersion + 1);
        wallet.UpdatedAt.Should().Be(_testNow);
        transaction.Amount.Should().Be(-200m);
        transaction.BalanceBefore.Should().Be(500m);
        transaction.BalanceAfter.Should().Be(300m);
    }

    [Fact]
    public void ConfirmFrozenDebit_InsufficientFrozenBalance_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(100m, _testNow);

        // Act
        var act = () => wallet.ConfirmFrozenDebit(200m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("*Frozen*");
    }

    [Fact]
    public void ConfirmFrozenDebit_ZeroAmount_ShouldThrowDomainException()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(200m, _testNow);

        // Act
        var act = () => wallet.ConfirmFrozenDebit(0m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        act.Should().Throw<DomainException>();
    }

    [Fact]
    public void ConfirmFrozenDebit_TransactionAmountShouldBeNegative()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        wallet.Freeze(200m, _testNow);

        // Act
        var transaction = wallet.ConfirmFrozenDebit(200m, TransactionType.Withdrawal, "Test", _testNow);

        // Assert
        transaction.Amount.Should().BeNegative();
    }

    #endregion

    #region Transaction Type Tests

    [Fact]
    public void Credit_WithOrderId_ShouldIncludeInTransaction()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        var orderId = Guid.NewGuid();

        // Act
        var transaction = wallet.Credit(100m, TransactionType.GameTransferOut, "Game return", _testNow, orderId);

        // Assert
        transaction.OrderId.Should().Be(orderId);
    }

    [Fact]
    public void Debit_WithOrderId_ShouldIncludeInTransaction()
    {
        // Arrange
        var wallet = Wallet.Create(_testUserId, _testNow);
        wallet.Credit(500m, TransactionType.Deposit, "Initial", _testNow);
        var orderId = Guid.NewGuid();

        // Act
        var transaction = wallet.Debit(100m, TransactionType.GameTransferIn, "Game transfer", _testNow, orderId);

        // Assert
        transaction.OrderId.Should().Be(orderId);
    }

    #endregion
}
