// AUTO-GENERATED BY CLAUDE
using FluentAssertions;
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using Xunit;

namespace GamePlatform.Domain.Tests.Entities;

public class WithdrawRequestTests
{
    private readonly Guid _testUserId = Guid.NewGuid();
    private readonly Guid _testBankCardId = Guid.NewGuid();
    private readonly string _testInternalOrderId = Guid.NewGuid().ToString("N");
    private readonly decimal _testAmount = 100m;
    private readonly DateTime _testNow = new(2026, 3, 10, 12, 0, 0);

    [Fact]
    public void Create_WithValidParameters_ShouldInitializeCorrectly()
    {
        // Act
        var request = WithdrawRequest.Create(
            _testUserId,
            _testInternalOrderId,
            _testAmount,
            _testBankCardId,
            _testNow);

        // Assert
        request.Id.Should().NotBe(Guid.Empty);
        request.UserId.Should().Be(_testUserId);
        request.InternalOrderId.Should().Be(_testInternalOrderId);
        request.ExternalOrderId.Should().BeNull();
        request.Amount.Should().Be(_testAmount);
        request.BankCardId.Should().Be(_testBankCardId);
        request.Status.Should().Be(WithdrawStatus.Pending);
        request.RejectionReason.Should().BeNull();
        request.CreatedAt.Should().Be(_testNow);
        request.UpdatedAt.Should().Be(_testNow);
    }

    [Fact]
    public void Create_WithEmptyUserId_ShouldThrowDomainException()
    {
        // Act
        var act = () => WithdrawRequest.Create(
            Guid.Empty,
            _testInternalOrderId,
            _testAmount,
            _testBankCardId,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("UserId cannot be empty*");
    }

    [Fact]
    public void Create_WithEmptyInternalOrderId_ShouldThrowDomainException()
    {
        // Act
        var act = () => WithdrawRequest.Create(
            _testUserId,
            "",
            _testAmount,
            _testBankCardId,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("InternalOrderId cannot be empty*");
    }

    [Fact]
    public void Create_WithZeroAmount_ShouldThrowDomainException()
    {
        // Act
        var act = () => WithdrawRequest.Create(
            _testUserId,
            _testInternalOrderId,
            0m,
            _testBankCardId,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("Amount must be positive*");
    }

    [Fact]
    public void Create_WithNegativeAmount_ShouldThrowDomainException()
    {
        // Act
        var act = () => WithdrawRequest.Create(
            _testUserId,
            _testInternalOrderId,
            -100m,
            _testBankCardId,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("Amount must be positive*");
    }

    [Fact]
    public void Create_WithEmptyBankCardId_ShouldThrowDomainException()
    {
        // Act
        var act = () => WithdrawRequest.Create(
            _testUserId,
            _testInternalOrderId,
            _testAmount,
            Guid.Empty,
            _testNow);

        // Assert
        act.Should().Throw<DomainException>()
            .WithMessage("BankCardId cannot be empty*");
    }

    [Fact]
    public void Approve_FromPendingStatus_ShouldUpdateStatus()
    {
        // Arrange
        var request = CreatePendingWithdraw();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Approve(newNow);

        // Assert
        request.Status.Should().Be(WithdrawStatus.Approved);
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Approve_FromNonPendingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreatePendingWithdraw();
        request.Approve(_testNow);

        // Act
        var act = () => request.Approve(_testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    [Fact]
    public void Reject_FromPendingStatus_ShouldUpdateStatusAndReason()
    {
        // Arrange
        var request = CreatePendingWithdraw();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Reject("Insufficient balance", newNow);

        // Assert
        request.Status.Should().Be(WithdrawStatus.Rejected);
        request.RejectionReason.Should().Be("Insufficient balance");
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Reject_FromNonPendingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreateApprovedWithdraw();

        // Act
        var act = () => request.Reject("Reason", _testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    [Fact]
    public void Process_FromApprovedStatus_ShouldUpdateStatusAndExternalOrderId()
    {
        // Arrange
        var request = CreateApprovedWithdraw();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Process("external-withdraw-123", newNow);

        // Assert
        request.Status.Should().Be(WithdrawStatus.Processing);
        request.ExternalOrderId.Should().Be("external-withdraw-123");
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Process_FromNonApprovedStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreatePendingWithdraw();

        // Act
        var act = () => request.Process("external-id", _testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    [Fact]
    public void Complete_FromProcessingStatus_ShouldUpdateStatus()
    {
        // Arrange
        var request = CreateProcessingWithdraw();
        var newNow = _testNow.AddHours(1);

        // Act
        request.Complete(newNow);

        // Assert
        request.Status.Should().Be(WithdrawStatus.Completed);
        request.UpdatedAt.Should().Be(newNow);
    }

    [Fact]
    public void Complete_FromNonProcessingStatus_ShouldThrowInvalidStateTransitionException()
    {
        // Arrange
        var request = CreateApprovedWithdraw();

        // Act
        var act = () => request.Complete(_testNow);

        // Assert
        act.Should().Throw<StateMachineException>();
    }

    #region Helper Methods

    private WithdrawRequest CreatePendingWithdraw()
    {
        return WithdrawRequest.Create(
            _testUserId,
            _testInternalOrderId,
            _testAmount,
            _testBankCardId,
            _testNow);
    }

    private WithdrawRequest CreateApprovedWithdraw()
    {
        var request = CreatePendingWithdraw();
        request.Approve(_testNow);
        return request;
    }

    private WithdrawRequest CreateProcessingWithdraw()
    {
        var request = CreateApprovedWithdraw();
        request.Process("external-withdraw-123", _testNow);
        return request;
    }

    #endregion
}
