// AUTO-GENERATED BY CLAUDE
using GamePlatform.Application.Interfaces;
using GamePlatform.Domain.Interfaces;
using GamePlatform.Infrastructure.Persistence;
using GamePlatform.Infrastructure.Persistence.Repositories;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

// Configure PostgreSQL with EF Core
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));

// Register repositories
builder.Services.AddScoped<IWalletRepository, WalletRepository>();
builder.Services.AddScoped<IOrderRepository, GameOrderRepository>();
builder.Services.AddScoped<IUserProfileRepository, UserProfileRepository>();
builder.Services.AddScoped<IVendorPlayerMappingRepository, VendorPlayerMappingRepository>();
builder.Services.AddScoped<IDepositRequestRepository, DepositRequestRepository>();
builder.Services.AddScoped<IWithdrawRequestRepository, WithdrawRequestRepository>();
builder.Services.AddScoped<IUserBankCardRepository, UserBankCardRepository>();
builder.Services.AddScoped<IUnitOfWork, UnitOfWork>();

// Register time provider
builder.Services.AddSingleton<ITimeProvider, SystemTimeProvider>();

// Configure CORS
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseCors();
app.UseAuthorization();
app.MapControllers();

app.Run();
