// AUTO-GENERATED BY CLAUDE
import { http, HttpResponse, delay } from 'msw'

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api'

export const handlers = [
  // Health check
  http.get(`${API_BASE_URL}/health`, async () => {
    await delay(100)
    return HttpResponse.json({ status: 'healthy' })
  }),

  // Auth endpoints
  http.post(`${API_BASE_URL}/auth/sync-profile`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: {
        id: 'test-user-id',
        username: 'testuser',
        role: 'User',
      },
    })
  }),

  http.get(`${API_BASE_URL}/auth/me`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: {
        id: 'test-user-id',
        username: 'testuser',
        nickname: 'Test User',
        role: 'User',
        status: 'Active',
      },
    })
  }),

  // Wallet endpoints
  http.get(`${API_BASE_URL}/wallet/balance`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: {
        balance: 10000.00,
        frozenBalance: 0,
        availableBalance: 10000.00,
      },
    })
  }),

  // Game endpoints
  http.get(`${API_BASE_URL}/games`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: [
        {
          gameCode: 'game-001',
          gameName: 'Test Game 1',
          platType: 'ag',
          gameType: '1',
        },
        {
          gameCode: 'game-002',
          gameName: 'Test Game 2',
          platType: 'pg',
          gameType: '2',
        },
      ],
    })
  }),
]

// Create a mock server for testing
export const createMockServer = () => {
  const { setupServer } = require('msw/node')
  return setupServer(...handlers)
}
