// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;

namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 充值申请仓储接口
/// </summary>
public interface IDepositRequestRepository
{
    Task<DepositRequest?> GetByIdAsync(Guid requestId);
    Task AddAsync(DepositRequest request);
    Task UpdateAsync(DepositRequest request);
    Task<IReadOnlyList<DepositRequest>> GetByStatusAsync(DepositStatus status, int page, int pageSize);
    Task<IReadOnlyList<DepositRequest>> GetByUserIdAsync(Guid userId, int page, int pageSize);
}
