// AUTO-GENERATED BY CLAUDE
namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 游戏投注记录仓储接口
/// </summary>
/// <remarks>
/// 注: GameBetRecord 实体将在后续阶段实现
/// </remarks>
public interface IGameBetRecordRepository
{
    // TODO: 待 GameBetRecord 实体实现后取消注释
    // Task UpsertBatchAsync(IReadOnlyList<GameBetRecord> records);
    // Task<IReadOnlyList<GameBetRecord>> GetByUserIdAsync(Guid userId, int page, int pageSize);
    // Task<IReadOnlyList<GameBetRecord>> GetPagedAsync(int page, int pageSize, string? platType = null, string? vendorPlayerId = null);
}
