// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;

namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 游戏订单仓储接口
/// </summary>
public interface IOrderRepository
{
    Task<GameOrder?> GetByIdAsync(Guid orderId);
    Task<GameOrder?> GetByInternalOrderIdAsync(string internalOrderId);
    Task<GameOrder?> GetByExternalOrderIdAsync(string externalOrderId);
    Task AddAsync(GameOrder order);
    Task UpdateAsync(GameOrder order);
    
    /// <summary>
    /// 获取超过指定时间的 Pending 状态订单（用于恢复任务）
    /// </summary>
    Task<IReadOnlyList<GameOrder>> GetPendingOrdersAsync(TimeSpan olderThan);
    
    /// <summary>
    /// 获取超过指定时间的 Confirmed 状态订单（用于轮询任务）
    /// </summary>
    Task<IReadOnlyList<GameOrder>> GetConfirmedOrdersAsync(TimeSpan olderThan);
    
    Task<IReadOnlyList<GameOrder>> GetByUserIdAsync(Guid userId, int page, int pageSize);
    
    /// <summary>
    /// 检查用户是否有进行中的订单（Pending 或 Confirmed）
    /// 用于单会话控制
    /// </summary>
    Task<bool> HasActiveOrderAsync(Guid userId);
}
