// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;

namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 用户资料仓储接口
/// </summary>
public interface IUserProfileRepository
{
    Task<UserProfile?> GetByIdAsync(Guid userId);
    Task AddAsync(UserProfile profile);
    Task UpdateAsync(UserProfile profile);
    Task<IReadOnlyList<UserProfile>> GetFilteredAsync(string? filter, int page, int pageSize);
    Task<IReadOnlyList<UserProfile>> GetByAgentIdAsync(Guid agentId, int page, int pageSize);
}
