// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;

namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 用户银行卡仓储接口
/// </summary>
public interface IUserBankCardRepository
{
    Task<UserBankCard?> GetByIdAsync(Guid cardId);
    Task<IReadOnlyList<UserBankCard>> GetByUserIdAsync(Guid userId);
    Task AddAsync(UserBankCard card);
    Task UpdateAsync(UserBankCard card);
    Task DeleteAsync(Guid cardId);
    Task<int> GetCountByUserIdAsync(Guid userId);
}
