// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;

namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 厂商玩家映射仓储接口
/// </summary>
public interface IVendorPlayerMappingRepository
{
    Task<VendorPlayerMapping?> GetAsync(Guid userId, string vendorCode);
    Task AddAsync(VendorPlayerMapping mapping);
    Task UpdateAsync(VendorPlayerMapping mapping);
}
