// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;

namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 钱包仓储接口
/// </summary>
public interface IWalletRepository
{
    Task<Wallet?> GetByUserIdAsync(Guid userId);
    Task<Wallet?> GetByIdAsync(Guid walletId);
    Task AddAsync(Wallet wallet);
    Task<bool> UpdateWithCasAsync(Wallet wallet, int expectedVersion);
    Task AddTransactionAsync(WalletTransaction transaction);
    Task<IReadOnlyList<WalletTransaction>> GetTransactionsAsync(Guid walletId, int page, int pageSize);
    Task<decimal> GetTransactionsSumAsync(Guid walletId);
}
