// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Entities;
using GamePlatform.Domain.Enums;

namespace GamePlatform.Domain.Interfaces;

/// <summary>
/// 提现申请仓储接口
/// </summary>
public interface IWithdrawRequestRepository
{
    Task<WithdrawRequest?> GetByIdAsync(Guid requestId);
    Task AddAsync(WithdrawRequest request);
    Task UpdateAsync(WithdrawRequest request);
    Task<IReadOnlyList<WithdrawRequest>> GetByStatusAsync(WithdrawStatus status, int page, int pageSize);
    Task<IReadOnlyList<WithdrawRequest>> GetByUserIdAsync(Guid userId, int page, int pageSize);
}
