// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Rules;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 充值请求
/// </summary>
public class DepositRequest
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }
    public string InternalOrderId { get; private set; }
    public string? ExternalOrderId { get; private set; }
    public decimal Amount { get; private set; }
    public string? PaymentMethod { get; private set; }
    public DepositStatus Status { get; private set; }
    public string? ErrorMessage { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private DepositRequest() { }

    /// <summary>
    /// 创建充值请求
    /// </summary>
    public static DepositRequest Create(
        Guid userId,
        string internalOrderId,
        decimal amount,
        string? paymentMethod,
        DateTime now)
    {
        if (userId == Guid.Empty)
        {
            throw new DomainException("UserId cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(internalOrderId))
        {
            throw new DomainException("InternalOrderId cannot be empty.");
        }

        if (amount <= 0)
        {
            throw new DomainException("Amount must be positive.");
        }

        return new DepositRequest
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            InternalOrderId = internalOrderId,
            ExternalOrderId = null,
            Amount = amount,
            PaymentMethod = paymentMethod,
            Status = DepositStatus.Pending,
            CreatedAt = now,
            UpdatedAt = now
        };
    }

    /// <summary>
    /// 确认充值（三方已确认收到支付）
    /// </summary>
    public void Confirm(string externalOrderId, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(externalOrderId))
        {
            throw new DomainException("ExternalOrderId cannot be empty.");
        }

        DepositStateMachine.ValidateTransition(Status, DepositStatus.Confirmed);

        ExternalOrderId = externalOrderId;
        Status = DepositStatus.Confirmed;
        UpdatedAt = now;
    }

    /// <summary>
    /// 结算充值（余额入账）
    /// </summary>
    public void Settle(DateTime now)
    {
        DepositStateMachine.ValidateTransition(Status, DepositStatus.Settled);

        Status = DepositStatus.Settled;
        UpdatedAt = now;
    }

    /// <summary>
    /// 取消充值
    /// </summary>
    public void Cancel(DateTime now)
    {
        DepositStateMachine.ValidateTransition(Status, DepositStatus.Cancelled);

        Status = DepositStatus.Cancelled;
        UpdatedAt = now;
    }

    /// <summary>
    /// 标记充值失败
    /// </summary>
    public void Fail(string errorMessage, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(errorMessage))
        {
            throw new DomainException("ErrorMessage cannot be empty.");
        }

        DepositStateMachine.ValidateTransition(Status, DepositStatus.Failed);

        ErrorMessage = errorMessage;
        Status = DepositStatus.Failed;
        UpdatedAt = now;
    }
}
