// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Rules;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 游戏订单
/// </summary>
public class GameOrder
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }
    public string VendorCode { get; private set; } = string.Empty;
    public string PlatType { get; private set; } = string.Empty;
    public string GameCode { get; private set; } = string.Empty;
    public string InternalOrderId { get; private set; } = string.Empty;
    public string? ExternalOrderId { get; private set; }
    public decimal TransferInAmount { get; private set; }
    public decimal? TransferOutAmount { get; private set; }
    public OrderStatus Status { get; private set; }
    public string? GameUrl { get; private set; }
    public string? ErrorMessage { get; private set; }
    public string? CancelReason { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    // EF Core 需要无参构造函数
    private GameOrder() { }

    private GameOrder(
        Guid userId,
        string vendorCode,
        string platType,
        string gameCode,
        string internalOrderId,
        decimal transferInAmount,
        DateTime now)
    {
        Id = Guid.NewGuid();
        UserId = userId;
        VendorCode = vendorCode;
        PlatType = platType;
        GameCode = gameCode;
        InternalOrderId = internalOrderId;
        TransferInAmount = transferInAmount;
        Status = OrderStatus.Pending;
        CreatedAt = now;
        UpdatedAt = now;
    }

    /// <summary>
    /// 创建游戏订单
    /// </summary>
    public static GameOrder Create(
        Guid userId,
        string vendorCode,
        string platType,
        string gameCode,
        string internalOrderId,
        decimal transferInAmount,
        DateTime now)
    {
        ValidateParameters(userId, vendorCode, platType, gameCode, internalOrderId, transferInAmount);

        return new GameOrder(
            userId,
            vendorCode,
            platType,
            gameCode,
            internalOrderId,
            transferInAmount,
            now);
    }

    private static void ValidateParameters(
        Guid userId,
        string vendorCode,
        string platType,
        string gameCode,
        string internalOrderId,
        decimal transferInAmount)
    {
        if (userId == Guid.Empty)
            {
                throw new DomainException("UserId cannot be empty.");
            }

        if (string.IsNullOrWhiteSpace(vendorCode))
        {
            throw new DomainException("VendorCode cannot be empty.");
            }

        if (string.IsNullOrWhiteSpace(platType))
        {
            throw new DomainException("PlatType cannot be empty.");
            }

        if (string.IsNullOrWhiteSpace(gameCode))
        {
            throw new DomainException("GameCode cannot be empty.");
            }

        if (string.IsNullOrWhiteSpace(internalOrderId))
        {
            throw new DomainException("InternalOrderId cannot be empty.");
            }

        if (transferInAmount < 0)
        {
            throw new DomainException("TransferInAmount cannot be negative.");
            }
    }

    /// <summary>
    /// 确认订单（设置 ExternalOrderId 和 GameUrl）
    /// </summary>
    public void Confirm(string externalOrderId, string gameUrl, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(externalOrderId))
        {
            throw new DomainException("ExternalOrderId cannot be empty.");
            }

        if (string.IsNullOrWhiteSpace(gameUrl))
        {
            throw new DomainException("GameUrl cannot be empty.");
            }

        OrderStateMachine.ValidateTransition(Status, OrderStatus.Confirmed);

        ExternalOrderId = externalOrderId;
        GameUrl = gameUrl;
        Status = OrderStatus.Confirmed;
        UpdatedAt = now;
    }

    /// <summary>
    /// 结算订单（设置 TransferOutAmount）
    /// </summary>
    public void Settle(decimal transferOutAmount, DateTime now)
    {
        if (transferOutAmount <= 0)
        {
            throw new DomainException("TransferOutAmount must be greater than zero.");
        }

        OrderStateMachine.ValidateTransition(Status, OrderStatus.Settled);

        TransferOutAmount = transferOutAmount;
        Status = OrderStatus.Settled;
        UpdatedAt = now;
    }

    /// <summary>
    /// 取消订单
    /// </summary>
    public void Cancel(string? reason, DateTime now)
    {
        OrderStateMachine.ValidateTransition(Status, OrderStatus.Cancelled);

        CancelReason = reason;
        Status = OrderStatus.Cancelled;
        UpdatedAt = now;
    }

    /// <summary>
    /// 标记订单失败
    /// </summary>
    public void Fail(string errorMessage, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(errorMessage))
        {
            throw new DomainException("ErrorMessage cannot be empty.");
        }

        OrderStateMachine.ValidateTransition(Status, OrderStatus.Failed);

        ErrorMessage = errorMessage;
        Status = OrderStatus.Failed;
        UpdatedAt = now;
    }
}
