// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 用户资料
/// </summary>
public class UserProfile
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }
    public string Username { get; private set; }
    public string? AvatarUrl { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private UserProfile() { }

    /// <summary>
    /// 创建用户资料
    /// </summary>
    public static UserProfile Create(Guid userId, string username, DateTime now)
    {
        if (userId == Guid.Empty)
        {
            throw new DomainException("UserId cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(username))
        {
            throw new DomainException("Username cannot be empty.");
        }

        return new UserProfile
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            Username = username,
            AvatarUrl = null,
            CreatedAt = now,
            UpdatedAt = now
        };
    }

    /// <summary>
    /// 更新用户名
    /// </summary>
    public void UpdateUsername(string username, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(username))
        {
            throw new DomainException("Username cannot be empty.");
        }

        Username = username;
        UpdatedAt = now;
    }

    /// <summary>
    /// 更新头像
    /// </summary>
    public void UpdateAvatar(string? avatarUrl, DateTime now)
    {
        AvatarUrl = avatarUrl;
        UpdatedAt = now;
    }
}
