// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 用户银行卡
/// </summary>
public class UserBankCard
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }
    public string BankName { get; private set; }
    public string BankCardNumber { get; private set; }
    public string AccountName { get; private set; }
    public bool IsDefault { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private UserBankCard() { }

    /// <summary>
    /// 创建用户银行卡
    /// </summary>
    public static UserBankCard Create(
        Guid userId,
        string bankName,
        string bankCardNumber,
        string accountName,
        DateTime now)
    {
        if (userId == Guid.Empty)
        {
            throw new DomainException("UserId cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(bankName))
        {
            throw new DomainException("BankName cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(bankCardNumber))
        {
            throw new DomainException("BankCardNumber cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(accountName))
        {
            throw new DomainException("AccountName cannot be empty.");
        }

        return new UserBankCard
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            BankName = bankName,
            BankCardNumber = bankCardNumber,
            AccountName = accountName,
            IsDefault = false,
            CreatedAt = now,
            UpdatedAt = now
        };
    }

    /// <summary>
    /// 设置为默认银行卡
    /// </summary>
    public void SetAsDefault(DateTime now)
    {
        IsDefault = true;
        UpdatedAt = now;
    }

    /// <summary>
    /// 取消默认银行卡
    /// </summary>
    public void UnsetAsDefault(DateTime now)
    {
        IsDefault = false;
        UpdatedAt = now;
    }

    /// <summary>
    /// 获取脱敏银行卡号（显示前4位和后4位，中间用星号代替）
    /// </summary>
    public string GetMaskedCardNumber()
    {
        if (BankCardNumber.Length <= 8)
        {
            return BankCardNumber;
        }

        var prefix = BankCardNumber.Substring(0, 4);
        var suffix = BankCardNumber.Substring(BankCardNumber.Length - 4);
        var middleStars = new string('*', 4);

        return $"{prefix} {middleStars} {middleStars} {suffix}";
    }
}
