// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Exceptions;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 声商玩家映射（内部用户ID与厂商玩家ID的关联）
/// </summary>
public class VendorPlayerMapping
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }
    public string VendorCode { get; private set; }
    public string VendorPlayerId { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private VendorPlayerMapping() { }

    /// <summary>
    /// 创建厂商玩家映射
    /// </summary>
    public static VendorPlayerMapping Create(
        Guid userId,
        string vendorCode,
        string vendorPlayerId,
        DateTime now)
    {
        if (userId == Guid.Empty)
        {
            throw new DomainException("UserId cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(vendorCode))
        {
            throw new DomainException("VendorCode cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(vendorPlayerId))
        {
            throw new DomainException("VendorPlayerId cannot be empty.");
        }

        return new VendorPlayerMapping
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            VendorCode = vendorCode,
            VendorPlayerId = vendorPlayerId,
            CreatedAt = now,
            UpdatedAt = now
        };
    }
}
