// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 钱包交易流水（不可删除）
/// </summary>
public class WalletTransaction
{
    public Guid Id { get; private set; }
    public Guid WalletId { get; private set; }
    public TransactionType Type { get; private set; }

    /// <summary>
    /// 交易金额（正 = 入账, 负 = 出账）
    /// </summary>
    public decimal Amount { get; private set; }

    public decimal BalanceBefore { get; private set; }
    public decimal BalanceAfter { get; private set; }
    public string Description { get; private set; } = string.Empty;
    public Guid? OrderId { get; private set; }
    public string? InternalOrderId { get; private set; }
    public DateTime CreatedAt { get; private set; }

    // EF Core 需要无参构造函数
    private WalletTransaction() { }

    internal WalletTransaction(
        Guid walletId,
        TransactionType type,
        decimal amount,
        decimal balanceBefore,
        decimal balanceAfter,
        string description,
        DateTime createdAt,
        Guid? orderId = null,
        string? internalOrderId = null)
    {
        Id = Guid.NewGuid();
        WalletId = walletId;
        Type = type;
        Amount = amount;
        BalanceBefore = balanceBefore;
        BalanceAfter = balanceAfter;
        Description = description;
        OrderId = orderId;
        InternalOrderId = internalOrderId;
        CreatedAt = createdAt;
    }
}
