// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Rules;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 用户钱包（CAS 乐观锁并发控制）
/// </summary>
public class Wallet
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }

    /// <summary>
    /// 钱包余额（必须 decimal，禁止 float/double）
    /// </summary>
    public decimal Balance { get; private set; }

    /// <summary>
    /// 冻结余额（提现申请冻结）
    /// </summary>
    public decimal FrozenBalance { get; private set; }

    /// <summary>
    /// CAS 乐观锁版本号
    /// </summary>
    public int Version { get; private set; }

    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    /// <summary>
    /// 可用余额 = Balance - FrozenBalance
    /// </summary>
    public decimal AvailableBalance => Balance - FrozenBalance;

    // EF Core 需要无参构造函数
    private Wallet() { }

    private Wallet(Guid userId, DateTime now)
    {
        Id = Guid.NewGuid();
        UserId = userId;
        Balance = 0;
        FrozenBalance = 0;
        Version = 0;
        CreatedAt = now;
        UpdatedAt = now;
    }

    /// <summary>
    /// 创建新钱包
    /// </summary>
    public static Wallet Create(Guid userId, DateTime now)
    {
        return new Wallet(userId, now);
    }

    /// <summary>
    /// 入账：充值、游戏转出、退款、管理员调整（正）
    /// </summary>
    public WalletTransaction Credit(
        decimal amount,
        TransactionType type,
        string description,
        DateTime now,
        Guid? orderId = null)
    {
        WalletRules.ValidateAmount(amount);

        var balanceBefore = Balance;
        Balance += amount;
        Version++;
        UpdatedAt = now;

        return new WalletTransaction(
            Id,
            type,
            amount, // 正值
            balanceBefore,
            Balance,
            description,
            now,
            orderId);
    }

    /// <summary>
    /// 出账：提现、游戏转入、管理员调整（负）
    /// </summary>
    public WalletTransaction Debit(
        decimal amount,
        TransactionType type,
        string description,
        DateTime now,
        Guid? orderId = null)
    {
        WalletRules.ValidateAmount(amount);
        WalletRules.ValidateSufficientBalance(AvailableBalance, amount);

        var balanceBefore = Balance;
        Balance -= amount;
        Version++;
        UpdatedAt = now;

        return new WalletTransaction(
            Id,
            type,
            -amount, // 负值
            balanceBefore,
            Balance,
            description,
            now,
            orderId);
    }

    /// <summary>
    /// 冻结余额（提现申请时调用）
    /// </summary>
    public void Freeze(decimal amount, DateTime now)
    {
        WalletRules.ValidateAmount(amount);
        WalletRules.ValidateSufficientBalance(AvailableBalance, amount);

        FrozenBalance += amount;
        Version++;
        UpdatedAt = now;
    }

    /// <summary>
    /// 解冻余额（提现拒绝/取消时调用）
    /// </summary>
    public void Unfreeze(decimal amount, DateTime now)
    {
        WalletRules.ValidateAmount(amount);
        WalletRules.ValidateSufficientFrozenBalance(FrozenBalance, amount);

        FrozenBalance -= amount;
        Version++;
        UpdatedAt = now;
    }

    /// <summary>
    /// 确认冻结扣款（提现审批通过时调用，从 Balance 和 FrozenBalance 同时扣减）
    /// </summary>
    public WalletTransaction ConfirmFrozenDebit(
        decimal amount,
        TransactionType type,
        string description,
        DateTime now,
        Guid? orderId = null)
    {
        WalletRules.ValidateAmount(amount);
        WalletRules.ValidateSufficientFrozenBalance(FrozenBalance, amount);

        var balanceBefore = Balance;
        Balance -= amount;
        FrozenBalance -= amount;
        Version++;
        UpdatedAt = now;

        return new WalletTransaction(
            Id,
            type,
            -amount, // 负值
            balanceBefore,
            Balance,
            description,
            now,
            orderId);
    }
}
