// AUTO-GENERATED BY CLAUDE
using GamePlatform.Domain.Enums;
using GamePlatform.Domain.Exceptions;
using GamePlatform.Domain.Rules;

namespace GamePlatform.Domain.Entities;

/// <summary>
/// 提现请求
/// </summary>
public class WithdrawRequest
{
    public Guid Id { get; private set; }
    public Guid UserId { get; private set; }
    public string InternalOrderId { get; private set; }
    public string? ExternalOrderId { get; private set; }
    public decimal Amount { get; private set; }
    public Guid BankCardId { get; private set; }
    public WithdrawStatus Status { get; private set; }
    public string? RejectionReason { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime UpdatedAt { get; private set; }

    private WithdrawRequest() { }

    /// <summary>
    /// 创建提现请求
    /// </summary>
    public static WithdrawRequest Create(
        Guid userId,
        string internalOrderId,
        decimal amount,
        Guid bankCardId,
        DateTime now)
    {
        if (userId == Guid.Empty)
        {
            throw new DomainException("UserId cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(internalOrderId))
        {
            throw new DomainException("InternalOrderId cannot be empty.");
        }

        if (amount <= 0)
        {
            throw new DomainException("Amount must be positive.");
        }

        if (bankCardId == Guid.Empty)
        {
            throw new DomainException("BankCardId cannot be empty.");
        }

        return new WithdrawRequest
        {
            Id = Guid.NewGuid(),
            UserId = userId,
            InternalOrderId = internalOrderId,
            ExternalOrderId = null,
            Amount = amount,
            BankCardId = bankCardId,
            Status = WithdrawStatus.Pending,
            CreatedAt = now,
            UpdatedAt = now
        };
    }

    /// <summary>
    /// 批准提现
    /// </summary>
    public void Approve(DateTime now)
    {
        WithdrawStateMachine.ValidateTransition(Status, WithdrawStatus.Approved);

        Status = WithdrawStatus.Approved;
        UpdatedAt = now;
    }

    /// <summary>
    /// 拒绝提现
    /// </summary>
    public void Reject(string reason, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(reason))
        {
            throw new DomainException("Rejection reason cannot be empty.");
        }

        WithdrawStateMachine.ValidateTransition(Status, WithdrawStatus.Rejected);

        RejectionReason = reason;
        Status = WithdrawStatus.Rejected;
        UpdatedAt = now;
    }

    /// <summary>
    /// 处理中（已提交到三方）
    /// </summary>
    public void Process(string externalOrderId, DateTime now)
    {
        if (string.IsNullOrWhiteSpace(externalOrderId))
        {
            throw new DomainException("ExternalOrderId cannot be empty.");
        }

        WithdrawStateMachine.ValidateTransition(Status, WithdrawStatus.Processing);

        ExternalOrderId = externalOrderId;
        Status = WithdrawStatus.Processing;
        UpdatedAt = now;
    }

    /// <summary>
    /// 完成提现
    /// </summary>
    public void Complete(DateTime now)
    {
        WithdrawStateMachine.ValidateTransition(Status, WithdrawStatus.Completed);

        Status = WithdrawStatus.Completed;
        UpdatedAt = now;
    }
}
