// AUTO-GENERATED BY CLAUDE
import { http, HttpResponse, delay } from 'msw'

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api'

export const handlers = [
  // Health check
  http.get(`${API_BASE_URL}/health`, async () => {
    await delay(100)
    return HttpResponse.json({ status: 'healthy' })
  }),

  // Admin Auth endpoints
  http.post(`${API_BASE_URL}/auth/sync-profile`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: {
        id: 'admin-user-id',
        username: 'admin',
        role: 'Admin',
      },
    })
  }),

  http.get(`${API_BASE_URL}/auth/me`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: {
        id: 'admin-user-id',
        username: 'admin',
        nickname: 'Administrator',
        role: 'Admin',
        status: 'Active',
      },
    })
  }),

  // Admin dashboard stats
  http.get(`${API_BASE_URL}/admin/dashboard/stats`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: {
        totalUsers: 1000,
        todayDeposits: 50000.00,
        todayWithdrawals: 30000.00,
        todayOrders: 500,
        pendingRequests: 10,
        newUsersToday: 25,
      },
    })
  }),

  // Admin user list
  http.get(`${API_BASE_URL}/admin/users`, async () => {
    await delay(100)
    return HttpResponse.json({
      success: true,
      data: [
        {
          id: 'user-001',
          username: 'user1',
          nickname: 'User One',
          role: 'User',
          status: 'Active',
          createdAt: '2025-01-01T00:00:00Z',
        },
        {
          id: 'user-002',
          username: 'user2',
          nickname: 'User Two',
          role: 'User',
          status: 'Active',
          createdAt: '2025-01-02T00:00:00Z',
        },
      ],
      meta: {
        page: 1,
        pageSize: 20,
        totalCount: 2,
        totalPages: 1,
      },
    })
  }),
]

// Create a mock server for testing
export const createMockServer = () => {
  const { setupServer } = require('msw/node')
  return setupServer(...handlers)
}
